// Generated by delombok at Wed Aug 05 15:39:27 IST 2026
package com.velora.notification.controller;

import com.velora.notification.entity.Notification;
import com.velora.notification.repository.NotificationRepository;
import com.velora.notification.common.ApiResponse;
import com.velora.notification.common.ResourceNotFoundException;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/notifications")
@Tag(name = "Notifications", description = "In-app notification management")
public class NotificationController {
    private final NotificationRepository notificationRepository;

    private Long parseUserId(String header) {
        if (header == null || header.isBlank())
            return 1L;
        try {
            return Long.parseLong(header);
        } catch (NumberFormatException e) {
            return 1L;
        }
    }

    @GetMapping
    @Operation(summary = "Get user notifications")
    public ResponseEntity<ApiResponse<Page<Notification>>> getNotifications(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader,
            @RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "20") int size) {
        Long userId = parseUserId(userIdHeader);
        Page<Notification> notifications = notificationRepository.findByUserIdOrderByCreatedAtDesc(userId,
                PageRequest.of(page, size, Sort.by("createdAt").descending()));
        return ResponseEntity.ok(ApiResponse.success("Notifications retrieved", notifications));
    }

    @GetMapping("/unread-count")
    @Operation(summary = "Get unread notification count")
    public ResponseEntity<ApiResponse<Long>> getUnreadCount(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader) {
        Long userId = parseUserId(userIdHeader);
        long count = notificationRepository.countByUserIdAndReadFalse(userId);
        return ResponseEntity.ok(ApiResponse.success("Unread count retrieved", count));
    }

    @PutMapping("/{id}/read")
    @Operation(summary = "Mark notification as read")
    @Transactional
    public ResponseEntity<ApiResponse<Void>> markAsRead(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @PathVariable Long id) {
        Notification notification = notificationRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Notification not found"));
        notification.setRead(true);
        notificationRepository.save(notification);
        return ResponseEntity.ok(ApiResponse.success("Notification marked as read", null));
    }

    @PutMapping("/mark-all-read")
    @Operation(summary = "Mark all notifications as read")
    @Transactional
    public ResponseEntity<ApiResponse<Integer>> markAllRead(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader) {
        Long userId = parseUserId(userIdHeader);
        int updated = notificationRepository.markAllReadByUserId(userId);
        return ResponseEntity.ok(ApiResponse.success("All notifications marked as read", updated));
    }

    @java.lang.SuppressWarnings("all")
    public NotificationController(final NotificationRepository notificationRepository) {
        this.notificationRepository = notificationRepository;
    }
}
