// Generated by delombok at Wed Aug 05 15:39:33 IST 2026
package com.velora.admin.dto;

import java.util.Map;

public class SystemHealthDto {
    private String status; // UP, DEGRADED, DOWN
    private long totalRegisteredUsers;
    private long totalActivePoliceUnits;
    private long totalIncidentsReported;
    private long totalSosDispatched;
    private Map<String, String> microservicesHealth;


    @java.lang.SuppressWarnings("all")
    public static class SystemHealthDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private String status;
        @java.lang.SuppressWarnings("all")
        private long totalRegisteredUsers;
        @java.lang.SuppressWarnings("all")
        private long totalActivePoliceUnits;
        @java.lang.SuppressWarnings("all")
        private long totalIncidentsReported;
        @java.lang.SuppressWarnings("all")
        private long totalSosDispatched;
        @java.lang.SuppressWarnings("all")
        private Map<String, String> microservicesHealth;

        @java.lang.SuppressWarnings("all")
        SystemHealthDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemHealthDto.SystemHealthDtoBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemHealthDto.SystemHealthDtoBuilder totalRegisteredUsers(final long totalRegisteredUsers) {
            this.totalRegisteredUsers = totalRegisteredUsers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemHealthDto.SystemHealthDtoBuilder totalActivePoliceUnits(final long totalActivePoliceUnits) {
            this.totalActivePoliceUnits = totalActivePoliceUnits;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemHealthDto.SystemHealthDtoBuilder totalIncidentsReported(final long totalIncidentsReported) {
            this.totalIncidentsReported = totalIncidentsReported;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemHealthDto.SystemHealthDtoBuilder totalSosDispatched(final long totalSosDispatched) {
            this.totalSosDispatched = totalSosDispatched;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemHealthDto.SystemHealthDtoBuilder microservicesHealth(final Map<String, String> microservicesHealth) {
            this.microservicesHealth = microservicesHealth;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SystemHealthDto build() {
            return new SystemHealthDto(this.status, this.totalRegisteredUsers, this.totalActivePoliceUnits, this.totalIncidentsReported, this.totalSosDispatched, this.microservicesHealth);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SystemHealthDto.SystemHealthDtoBuilder(status=" + this.status + ", totalRegisteredUsers=" + this.totalRegisteredUsers + ", totalActivePoliceUnits=" + this.totalActivePoliceUnits + ", totalIncidentsReported=" + this.totalIncidentsReported + ", totalSosDispatched=" + this.totalSosDispatched + ", microservicesHealth=" + this.microservicesHealth + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SystemHealthDto.SystemHealthDtoBuilder builder() {
        return new SystemHealthDto.SystemHealthDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalRegisteredUsers() {
        return this.totalRegisteredUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalActivePoliceUnits() {
        return this.totalActivePoliceUnits;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalIncidentsReported() {
        return this.totalIncidentsReported;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalSosDispatched() {
        return this.totalSosDispatched;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, String> getMicroservicesHealth() {
        return this.microservicesHealth;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalRegisteredUsers(final long totalRegisteredUsers) {
        this.totalRegisteredUsers = totalRegisteredUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalActivePoliceUnits(final long totalActivePoliceUnits) {
        this.totalActivePoliceUnits = totalActivePoliceUnits;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalIncidentsReported(final long totalIncidentsReported) {
        this.totalIncidentsReported = totalIncidentsReported;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalSosDispatched(final long totalSosDispatched) {
        this.totalSosDispatched = totalSosDispatched;
    }

    @java.lang.SuppressWarnings("all")
    public void setMicroservicesHealth(final Map<String, String> microservicesHealth) {
        this.microservicesHealth = microservicesHealth;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SystemHealthDto)) return false;
        final SystemHealthDto other = (SystemHealthDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalRegisteredUsers() != other.getTotalRegisteredUsers()) return false;
        if (this.getTotalActivePoliceUnits() != other.getTotalActivePoliceUnits()) return false;
        if (this.getTotalIncidentsReported() != other.getTotalIncidentsReported()) return false;
        if (this.getTotalSosDispatched() != other.getTotalSosDispatched()) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$microservicesHealth = this.getMicroservicesHealth();
        final java.lang.Object other$microservicesHealth = other.getMicroservicesHealth();
        if (this$microservicesHealth == null ? other$microservicesHealth != null : !this$microservicesHealth.equals(other$microservicesHealth)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SystemHealthDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalRegisteredUsers = this.getTotalRegisteredUsers();
        result = result * PRIME + (int) ($totalRegisteredUsers >>> 32 ^ $totalRegisteredUsers);
        final long $totalActivePoliceUnits = this.getTotalActivePoliceUnits();
        result = result * PRIME + (int) ($totalActivePoliceUnits >>> 32 ^ $totalActivePoliceUnits);
        final long $totalIncidentsReported = this.getTotalIncidentsReported();
        result = result * PRIME + (int) ($totalIncidentsReported >>> 32 ^ $totalIncidentsReported);
        final long $totalSosDispatched = this.getTotalSosDispatched();
        result = result * PRIME + (int) ($totalSosDispatched >>> 32 ^ $totalSosDispatched);
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $microservicesHealth = this.getMicroservicesHealth();
        result = result * PRIME + ($microservicesHealth == null ? 43 : $microservicesHealth.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SystemHealthDto(status=" + this.getStatus() + ", totalRegisteredUsers=" + this.getTotalRegisteredUsers() + ", totalActivePoliceUnits=" + this.getTotalActivePoliceUnits() + ", totalIncidentsReported=" + this.getTotalIncidentsReported() + ", totalSosDispatched=" + this.getTotalSosDispatched() + ", microservicesHealth=" + this.getMicroservicesHealth() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SystemHealthDto() {
    }

    @java.lang.SuppressWarnings("all")
    public SystemHealthDto(final String status, final long totalRegisteredUsers, final long totalActivePoliceUnits, final long totalIncidentsReported, final long totalSosDispatched, final Map<String, String> microservicesHealth) {
        this.status = status;
        this.totalRegisteredUsers = totalRegisteredUsers;
        this.totalActivePoliceUnits = totalActivePoliceUnits;
        this.totalIncidentsReported = totalIncidentsReported;
        this.totalSosDispatched = totalSosDispatched;
        this.microservicesHealth = microservicesHealth;
    }
}
