// Generated by delombok at Wed Aug 05 15:39:33 IST 2026
package com.velora.admin.dto;

import jakarta.validation.constraints.NotBlank;

public class SystemSettingDto {
    private Long id;
    @NotBlank(message = "Setting key is required")
    private String settingKey;
    @NotBlank(message = "Setting value is required")
    private String settingValue;
    private String description;


    @java.lang.SuppressWarnings("all")
    public static class SystemSettingDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String settingKey;
        @java.lang.SuppressWarnings("all")
        private String settingValue;
        @java.lang.SuppressWarnings("all")
        private String description;

        @java.lang.SuppressWarnings("all")
        SystemSettingDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSettingDto.SystemSettingDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSettingDto.SystemSettingDtoBuilder settingKey(final String settingKey) {
            this.settingKey = settingKey;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSettingDto.SystemSettingDtoBuilder settingValue(final String settingValue) {
            this.settingValue = settingValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSettingDto.SystemSettingDtoBuilder description(final String description) {
            this.description = description;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SystemSettingDto build() {
            return new SystemSettingDto(this.id, this.settingKey, this.settingValue, this.description);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SystemSettingDto.SystemSettingDtoBuilder(id=" + this.id + ", settingKey=" + this.settingKey + ", settingValue=" + this.settingValue + ", description=" + this.description + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SystemSettingDto.SystemSettingDtoBuilder builder() {
        return new SystemSettingDto.SystemSettingDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getSettingKey() {
        return this.settingKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getSettingValue() {
        return this.settingValue;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSettingKey(final String settingKey) {
        this.settingKey = settingKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setSettingValue(final String settingValue) {
        this.settingValue = settingValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SystemSettingDto)) return false;
        final SystemSettingDto other = (SystemSettingDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$settingKey = this.getSettingKey();
        final java.lang.Object other$settingKey = other.getSettingKey();
        if (this$settingKey == null ? other$settingKey != null : !this$settingKey.equals(other$settingKey)) return false;
        final java.lang.Object this$settingValue = this.getSettingValue();
        final java.lang.Object other$settingValue = other.getSettingValue();
        if (this$settingValue == null ? other$settingValue != null : !this$settingValue.equals(other$settingValue)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SystemSettingDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $settingKey = this.getSettingKey();
        result = result * PRIME + ($settingKey == null ? 43 : $settingKey.hashCode());
        final java.lang.Object $settingValue = this.getSettingValue();
        result = result * PRIME + ($settingValue == null ? 43 : $settingValue.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SystemSettingDto(id=" + this.getId() + ", settingKey=" + this.getSettingKey() + ", settingValue=" + this.getSettingValue() + ", description=" + this.getDescription() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SystemSettingDto() {
    }

    @java.lang.SuppressWarnings("all")
    public SystemSettingDto(final Long id, final String settingKey, final String settingValue, final String description) {
        this.id = id;
        this.settingKey = settingKey;
        this.settingValue = settingValue;
        this.description = description;
    }
}
