// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.controller;

import com.velora.ai.dto.*;
import com.velora.ai.service.AiService;
import com.velora.ai.common.ApiResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/ai")
@Tag(name = "AI Safety", description = "AI chat assistant, risk prediction, and route recommendation")
public class AiController {
    private final AiService aiService;

    @PostMapping("/chat")
    @Operation(summary = "Chat with Velora AI safety assistant")
    public ResponseEntity<ApiResponse<AiChatResponse>> chat(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @Valid @RequestBody AiChatRequest request) {
        Long userId = (userIdHeader != null && !userIdHeader.isBlank()) ? Long.parseLong(userIdHeader) : null;
        AiChatResponse response = aiService.chat(request, userId);
        return ResponseEntity.ok(ApiResponse.success("AI response generated", response));
    }

    @PostMapping("/risk-prediction")
    @Operation(summary = "Predict safety risk for a location")
    public ResponseEntity<ApiResponse<RiskPredictionResponse>> predictRisk(@Valid @RequestBody RiskPredictionRequest request) {
        RiskPredictionResponse response = aiService.predictRisk(request);
        return ResponseEntity.ok(ApiResponse.success("Risk prediction completed", response));
    }

    @PostMapping({"/safe-route", "/route-recommendation"})
    @Operation(summary = "Get AI-powered safe route recommendation")
    public ResponseEntity<ApiResponse<RouteRecommendationResponse>> recommendRoute(@Valid @RequestBody RouteRecommendationRequest request) {
        RouteRecommendationResponse response = aiService.recommendRoute(request);
        return ResponseEntity.ok(ApiResponse.success("Route recommendation generated", response));
    }

    @java.lang.SuppressWarnings("all")
    public AiController(final AiService aiService) {
        this.aiService = aiService;
    }
}
