// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.controller;

import com.velora.user.common.ApiResponse;
import com.velora.user.dto.*;
import com.velora.user.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.List;

@RestController
@RequestMapping("/api/v1/users")
@Tag(name = "User Profile", description = "APIs for managing user profiles and emergency contacts")
@SecurityRequirement(name = "BearerAuth")
public class UserController {
    private final UserService userService;

    private Long extractUserId(String userIdHeader) {
        if (userIdHeader == null || userIdHeader.isBlank()) {
            return 1L;
        }
        try {
            return Long.parseLong(userIdHeader);
        } catch (NumberFormatException e) {
            return 1L;
        }
    }

    // ─── Profile Endpoints ───────────────────────────────────────────────────
    @GetMapping("/profile")
    @Operation(summary = "Get current user's profile")
    public ResponseEntity<ApiResponse<UserProfileResponse>> getMyProfile(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader) {
        Long userId = extractUserId(userIdHeader);
        UserProfileResponse profile = userService.getProfile(userId);
        return ResponseEntity.ok(ApiResponse.success("Profile retrieved successfully", profile));
    }

    @PutMapping("/profile")
    @Operation(summary = "Update current user\'s profile")
    public ResponseEntity<ApiResponse<UserProfileResponse>> updateMyProfile(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @Valid @RequestBody UpdateProfileRequest request) {
        Long userId = extractUserId(userIdHeader);
        UserProfileResponse profile = userService.updateProfile(userId, request);
        return ResponseEntity.ok(ApiResponse.success("Profile updated successfully", profile));
    }

    @PostMapping(value = "/profile/image", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(summary = "Upload profile image")
    public ResponseEntity<ApiResponse<String>> uploadProfileImage(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @RequestPart("file") MultipartFile file) {
        Long userId = extractUserId(userIdHeader);
        String imageUrl = userService.uploadProfileImage(userId, file);
        return ResponseEntity.ok(ApiResponse.success("Profile image uploaded successfully", imageUrl));
    }

    // ─── Emergency Contacts Endpoints ────────────────────────────────────────
    @GetMapping("/emergency-contacts")
    @Operation(summary = "Get all emergency contacts")
    public ResponseEntity<ApiResponse<List<EmergencyContactResponse>>> getEmergencyContacts(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader) {
        Long userId = extractUserId(userIdHeader);
        List<EmergencyContactResponse> contacts = userService.getEmergencyContacts(userId);
        return ResponseEntity.ok(ApiResponse.success("Emergency contacts retrieved", contacts));
    }

    @PostMapping("/emergency-contacts")
    @Operation(summary = "Add emergency contact")
    public ResponseEntity<ApiResponse<EmergencyContactResponse>> addEmergencyContact(@RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader, @Valid @RequestBody EmergencyContactRequest request) {
        Long userId = extractUserId(userIdHeader);
        EmergencyContactResponse contact = userService.addEmergencyContact(userId, request);
        return ResponseEntity.ok(ApiResponse.success("Emergency contact added", contact));
    }

    @PutMapping({"/emergency-contacts/{contactId}", "/emergency-contacts/{id}"})
    @Operation(summary = "Update emergency contact")
    public ResponseEntity<ApiResponse<EmergencyContactResponse>> updateEmergencyContact(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader,
            @PathVariable(value = "contactId", required = false) Long contactId,
            @PathVariable(value = "id", required = false) Long id,
            @Valid @RequestBody EmergencyContactRequest request) {
        Long userId = extractUserId(userIdHeader);
        Long targetId = contactId != null ? contactId : id;
        EmergencyContactResponse contact = userService.updateEmergencyContact(userId, targetId, request);
        return ResponseEntity.ok(ApiResponse.success("Emergency contact updated", contact));
    }

    @DeleteMapping({"/emergency-contacts/{contactId}", "/emergency-contacts/{id}"})
    @Operation(summary = "Delete emergency contact")
    public ResponseEntity<ApiResponse<Void>> deleteEmergencyContact(
            @RequestHeader(value = "X-Velora-User-Id", required = false) String userIdHeader,
            @PathVariable(value = "contactId", required = false) Long contactId,
            @PathVariable(value = "id", required = false) Long id) {
        Long userId = extractUserId(userIdHeader);
        Long targetId = contactId != null ? contactId : id;
        userService.deleteEmergencyContact(userId, targetId);
        return ResponseEntity.ok(ApiResponse.success("Emergency contact deleted", null));
    }

    @java.lang.SuppressWarnings("all")
    public UserController(final UserService userService) {
        this.userService = userService;
    }
}
