// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class EmergencyContactRequest {
    @NotBlank(message = "Contact name is required")
    @Size(max = 100, message = "Name cannot exceed 100 characters")
    private String name;
    @NotBlank(message = "Phone number is required")
    @Size(max = 20, message = "Phone number cannot exceed 20 characters")
    private String phoneNumber;
    @Size(max = 150, message = "Email cannot exceed 150 characters")
    private String email;
    @Size(max = 50, message = "Relationship cannot exceed 50 characters")
    private String relationship;
    private boolean primary;
    private boolean notifyOnSos;
    private boolean notifyOnRouteDeviation;


    @java.lang.SuppressWarnings("all")
    public static class EmergencyContactRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private String email;
        @java.lang.SuppressWarnings("all")
        private String relationship;
        @java.lang.SuppressWarnings("all")
        private boolean primary;
        @java.lang.SuppressWarnings("all")
        private boolean notifyOnSos;
        @java.lang.SuppressWarnings("all")
        private boolean notifyOnRouteDeviation;

        @java.lang.SuppressWarnings("all")
        EmergencyContactRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder relationship(final String relationship) {
            this.relationship = relationship;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder primary(final boolean primary) {
            this.primary = primary;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder notifyOnSos(final boolean notifyOnSos) {
            this.notifyOnSos = notifyOnSos;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest.EmergencyContactRequestBuilder notifyOnRouteDeviation(final boolean notifyOnRouteDeviation) {
            this.notifyOnRouteDeviation = notifyOnRouteDeviation;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public EmergencyContactRequest build() {
            return new EmergencyContactRequest(this.name, this.phoneNumber, this.email, this.relationship, this.primary, this.notifyOnSos, this.notifyOnRouteDeviation);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "EmergencyContactRequest.EmergencyContactRequestBuilder(name=" + this.name + ", phoneNumber=" + this.phoneNumber + ", email=" + this.email + ", relationship=" + this.relationship + ", primary=" + this.primary + ", notifyOnSos=" + this.notifyOnSos + ", notifyOnRouteDeviation=" + this.notifyOnRouteDeviation + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static EmergencyContactRequest.EmergencyContactRequestBuilder builder() {
        return new EmergencyContactRequest.EmergencyContactRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getRelationship() {
        return this.relationship;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isPrimary() {
        return this.primary;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isNotifyOnSos() {
        return this.notifyOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isNotifyOnRouteDeviation() {
        return this.notifyOnRouteDeviation;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setRelationship(final String relationship) {
        this.relationship = relationship;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrimary(final boolean primary) {
        this.primary = primary;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotifyOnSos(final boolean notifyOnSos) {
        this.notifyOnSos = notifyOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotifyOnRouteDeviation(final boolean notifyOnRouteDeviation) {
        this.notifyOnRouteDeviation = notifyOnRouteDeviation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EmergencyContactRequest)) return false;
        final EmergencyContactRequest other = (EmergencyContactRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isPrimary() != other.isPrimary()) return false;
        if (this.isNotifyOnSos() != other.isNotifyOnSos()) return false;
        if (this.isNotifyOnRouteDeviation() != other.isNotifyOnRouteDeviation()) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$relationship = this.getRelationship();
        final java.lang.Object other$relationship = other.getRelationship();
        if (this$relationship == null ? other$relationship != null : !this$relationship.equals(other$relationship)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EmergencyContactRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isPrimary() ? 79 : 97);
        result = result * PRIME + (this.isNotifyOnSos() ? 79 : 97);
        result = result * PRIME + (this.isNotifyOnRouteDeviation() ? 79 : 97);
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $relationship = this.getRelationship();
        result = result * PRIME + ($relationship == null ? 43 : $relationship.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "EmergencyContactRequest(name=" + this.getName() + ", phoneNumber=" + this.getPhoneNumber() + ", email=" + this.getEmail() + ", relationship=" + this.getRelationship() + ", primary=" + this.isPrimary() + ", notifyOnSos=" + this.isNotifyOnSos() + ", notifyOnRouteDeviation=" + this.isNotifyOnRouteDeviation() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public EmergencyContactRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public EmergencyContactRequest(final String name, final String phoneNumber, final String email, final String relationship, final boolean primary, final boolean notifyOnSos, final boolean notifyOnRouteDeviation) {
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.relationship = relationship;
        this.primary = primary;
        this.notifyOnSos = notifyOnSos;
        this.notifyOnRouteDeviation = notifyOnRouteDeviation;
    }
}
