// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.dto;

import jakarta.validation.constraints.NotBlank;

public class EmergencyContactDto {
    private Long id;
    private Long userId;
    @NotBlank(message = "Contact name is required")
    private String contactName;
    @NotBlank(message = "Phone number is required")
    private String phoneNumber;
    private String relationship;
    private int priorityOrder;


    @java.lang.SuppressWarnings("all")
    public static class EmergencyContactDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String contactName;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private String relationship;
        @java.lang.SuppressWarnings("all")
        private int priorityOrder;

        @java.lang.SuppressWarnings("all")
        EmergencyContactDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto.EmergencyContactDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto.EmergencyContactDtoBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto.EmergencyContactDtoBuilder contactName(final String contactName) {
            this.contactName = contactName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto.EmergencyContactDtoBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto.EmergencyContactDtoBuilder relationship(final String relationship) {
            this.relationship = relationship;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto.EmergencyContactDtoBuilder priorityOrder(final int priorityOrder) {
            this.priorityOrder = priorityOrder;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public EmergencyContactDto build() {
            return new EmergencyContactDto(this.id, this.userId, this.contactName, this.phoneNumber, this.relationship, this.priorityOrder);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "EmergencyContactDto.EmergencyContactDtoBuilder(id=" + this.id + ", userId=" + this.userId + ", contactName=" + this.contactName + ", phoneNumber=" + this.phoneNumber + ", relationship=" + this.relationship + ", priorityOrder=" + this.priorityOrder + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static EmergencyContactDto.EmergencyContactDtoBuilder builder() {
        return new EmergencyContactDto.EmergencyContactDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getContactName() {
        return this.contactName;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getRelationship() {
        return this.relationship;
    }

    @java.lang.SuppressWarnings("all")
    public int getPriorityOrder() {
        return this.priorityOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setContactName(final String contactName) {
        this.contactName = contactName;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setRelationship(final String relationship) {
        this.relationship = relationship;
    }

    @java.lang.SuppressWarnings("all")
    public void setPriorityOrder(final int priorityOrder) {
        this.priorityOrder = priorityOrder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EmergencyContactDto)) return false;
        final EmergencyContactDto other = (EmergencyContactDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getPriorityOrder() != other.getPriorityOrder()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$contactName = this.getContactName();
        final java.lang.Object other$contactName = other.getContactName();
        if (this$contactName == null ? other$contactName != null : !this$contactName.equals(other$contactName)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        final java.lang.Object this$relationship = this.getRelationship();
        final java.lang.Object other$relationship = other.getRelationship();
        if (this$relationship == null ? other$relationship != null : !this$relationship.equals(other$relationship)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EmergencyContactDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getPriorityOrder();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $contactName = this.getContactName();
        result = result * PRIME + ($contactName == null ? 43 : $contactName.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        final java.lang.Object $relationship = this.getRelationship();
        result = result * PRIME + ($relationship == null ? 43 : $relationship.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "EmergencyContactDto(id=" + this.getId() + ", userId=" + this.getUserId() + ", contactName=" + this.getContactName() + ", phoneNumber=" + this.getPhoneNumber() + ", relationship=" + this.getRelationship() + ", priorityOrder=" + this.getPriorityOrder() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public EmergencyContactDto() {
    }

    @java.lang.SuppressWarnings("all")
    public EmergencyContactDto(final Long id, final Long userId, final String contactName, final String phoneNumber, final String relationship, final int priorityOrder) {
        this.id = id;
        this.userId = userId;
        this.contactName = contactName;
        this.phoneNumber = phoneNumber;
        this.relationship = relationship;
        this.priorityOrder = priorityOrder;
    }
}
