// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Size;

public class UpdateProfileRequest {
    @Size(min = 2, max = 150, message = "Full name must be between 2 and 150 characters")
    private String fullName;
    @Email(message = "Invalid email format")
    private String email;
    @Size(max = 20, message = "Phone number cannot exceed 20 characters")
    private String phoneNumber;
    private String dateOfBirth;
    private String gender;
    private String address;
    private String city;
    private String state;
    private String country;
    private Double homeLatitude;
    private Double homeLongitude;
    private Double workLatitude;
    private Double workLongitude;
    private Boolean notificationEnabled;
    private Boolean locationSharingEnabled;
    private Boolean privacyModeEnabled;
    private String bloodGroup;
    private String emergencyNotes;


    @java.lang.SuppressWarnings("all")
    public static class UpdateProfileRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private String fullName;
        @java.lang.SuppressWarnings("all")
        private String email;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private String dateOfBirth;
        @java.lang.SuppressWarnings("all")
        private String gender;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private String city;
        @java.lang.SuppressWarnings("all")
        private String state;
        @java.lang.SuppressWarnings("all")
        private String country;
        @java.lang.SuppressWarnings("all")
        private Double homeLatitude;
        @java.lang.SuppressWarnings("all")
        private Double homeLongitude;
        @java.lang.SuppressWarnings("all")
        private Double workLatitude;
        @java.lang.SuppressWarnings("all")
        private Double workLongitude;
        @java.lang.SuppressWarnings("all")
        private Boolean notificationEnabled;
        @java.lang.SuppressWarnings("all")
        private Boolean locationSharingEnabled;
        @java.lang.SuppressWarnings("all")
        private Boolean privacyModeEnabled;

        @java.lang.SuppressWarnings("all")
        UpdateProfileRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder fullName(final String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder dateOfBirth(final String dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder gender(final String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder state(final String state) {
            this.state = state;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder homeLatitude(final Double homeLatitude) {
            this.homeLatitude = homeLatitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder homeLongitude(final Double homeLongitude) {
            this.homeLongitude = homeLongitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder workLatitude(final Double workLatitude) {
            this.workLatitude = workLatitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder workLongitude(final Double workLongitude) {
            this.workLongitude = workLongitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder notificationEnabled(final Boolean notificationEnabled) {
            this.notificationEnabled = notificationEnabled;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder locationSharingEnabled(final Boolean locationSharingEnabled) {
            this.locationSharingEnabled = locationSharingEnabled;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest.UpdateProfileRequestBuilder privacyModeEnabled(final Boolean privacyModeEnabled) {
            this.privacyModeEnabled = privacyModeEnabled;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public UpdateProfileRequest build() {
            return new UpdateProfileRequest(this.fullName, this.email, this.phoneNumber, this.dateOfBirth, this.gender, this.address, this.city, this.state, this.country, this.homeLatitude, this.homeLongitude, this.workLatitude, this.workLongitude, this.notificationEnabled, this.locationSharingEnabled, this.privacyModeEnabled);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "UpdateProfileRequest.UpdateProfileRequestBuilder(fullName=" + this.fullName + ", email=" + this.email + ", phoneNumber=" + this.phoneNumber + ", dateOfBirth=" + this.dateOfBirth + ", gender=" + this.gender + ", address=" + this.address + ", city=" + this.city + ", state=" + this.state + ", country=" + this.country + ", homeLatitude=" + this.homeLatitude + ", homeLongitude=" + this.homeLongitude + ", workLatitude=" + this.workLatitude + ", workLongitude=" + this.workLongitude + ", notificationEnabled=" + this.notificationEnabled + ", locationSharingEnabled=" + this.locationSharingEnabled + ", privacyModeEnabled=" + this.privacyModeEnabled + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static UpdateProfileRequest.UpdateProfileRequestBuilder builder() {
        return new UpdateProfileRequest.UpdateProfileRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    public String getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public String getCountry() {
        return this.country;
    }

    @java.lang.SuppressWarnings("all")
    public Double getHomeLatitude() {
        return this.homeLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getHomeLongitude() {
        return this.homeLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getWorkLatitude() {
        return this.workLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getWorkLongitude() {
        return this.workLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getNotificationEnabled() {
        return this.notificationEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getLocationSharingEnabled() {
        return this.locationSharingEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getPrivacyModeEnabled() {
        return this.privacyModeEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setDateOfBirth(final String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    public void setGender(final String gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setCountry(final String country) {
        this.country = country;
    }

    @java.lang.SuppressWarnings("all")
    public void setHomeLatitude(final Double homeLatitude) {
        this.homeLatitude = homeLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setHomeLongitude(final Double homeLongitude) {
        this.homeLongitude = homeLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setWorkLatitude(final Double workLatitude) {
        this.workLatitude = workLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setWorkLongitude(final Double workLongitude) {
        this.workLongitude = workLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationEnabled(final Boolean notificationEnabled) {
        this.notificationEnabled = notificationEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setLocationSharingEnabled(final Boolean locationSharingEnabled) {
        this.locationSharingEnabled = locationSharingEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrivacyModeEnabled(final Boolean privacyModeEnabled) {
        this.privacyModeEnabled = privacyModeEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public String getBloodGroup() {
        return this.bloodGroup;
    }

    @java.lang.SuppressWarnings("all")
    public void setBloodGroup(final String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmergencyNotes() {
        return this.emergencyNotes;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmergencyNotes(final String emergencyNotes) {
        this.emergencyNotes = emergencyNotes;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UpdateProfileRequest)) return false;
        final UpdateProfileRequest other = (UpdateProfileRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$homeLatitude = this.getHomeLatitude();
        final java.lang.Object other$homeLatitude = other.getHomeLatitude();
        if (this$homeLatitude == null ? other$homeLatitude != null : !this$homeLatitude.equals(other$homeLatitude)) return false;
        final java.lang.Object this$homeLongitude = this.getHomeLongitude();
        final java.lang.Object other$homeLongitude = other.getHomeLongitude();
        if (this$homeLongitude == null ? other$homeLongitude != null : !this$homeLongitude.equals(other$homeLongitude)) return false;
        final java.lang.Object this$workLatitude = this.getWorkLatitude();
        final java.lang.Object other$workLatitude = other.getWorkLatitude();
        if (this$workLatitude == null ? other$workLatitude != null : !this$workLatitude.equals(other$workLatitude)) return false;
        final java.lang.Object this$workLongitude = this.getWorkLongitude();
        final java.lang.Object other$workLongitude = other.getWorkLongitude();
        if (this$workLongitude == null ? other$workLongitude != null : !this$workLongitude.equals(other$workLongitude)) return false;
        final java.lang.Object this$notificationEnabled = this.getNotificationEnabled();
        final java.lang.Object other$notificationEnabled = other.getNotificationEnabled();
        if (this$notificationEnabled == null ? other$notificationEnabled != null : !this$notificationEnabled.equals(other$notificationEnabled)) return false;
        final java.lang.Object this$locationSharingEnabled = this.getLocationSharingEnabled();
        final java.lang.Object other$locationSharingEnabled = other.getLocationSharingEnabled();
        if (this$locationSharingEnabled == null ? other$locationSharingEnabled != null : !this$locationSharingEnabled.equals(other$locationSharingEnabled)) return false;
        final java.lang.Object this$privacyModeEnabled = this.getPrivacyModeEnabled();
        final java.lang.Object other$privacyModeEnabled = other.getPrivacyModeEnabled();
        if (this$privacyModeEnabled == null ? other$privacyModeEnabled != null : !this$privacyModeEnabled.equals(other$privacyModeEnabled)) return false;
        final java.lang.Object this$fullName = this.getFullName();
        final java.lang.Object other$fullName = other.getFullName();
        if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        final java.lang.Object this$dateOfBirth = this.getDateOfBirth();
        final java.lang.Object other$dateOfBirth = other.getDateOfBirth();
        if (this$dateOfBirth == null ? other$dateOfBirth != null : !this$dateOfBirth.equals(other$dateOfBirth)) return false;
        final java.lang.Object this$gender = this.getGender();
        final java.lang.Object other$gender = other.getGender();
        if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$country = this.getCountry();
        final java.lang.Object other$country = other.getCountry();
        if (this$country == null ? other$country != null : !this$country.equals(other$country)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UpdateProfileRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $homeLatitude = this.getHomeLatitude();
        result = result * PRIME + ($homeLatitude == null ? 43 : $homeLatitude.hashCode());
        final java.lang.Object $homeLongitude = this.getHomeLongitude();
        result = result * PRIME + ($homeLongitude == null ? 43 : $homeLongitude.hashCode());
        final java.lang.Object $workLatitude = this.getWorkLatitude();
        result = result * PRIME + ($workLatitude == null ? 43 : $workLatitude.hashCode());
        final java.lang.Object $workLongitude = this.getWorkLongitude();
        result = result * PRIME + ($workLongitude == null ? 43 : $workLongitude.hashCode());
        final java.lang.Object $notificationEnabled = this.getNotificationEnabled();
        result = result * PRIME + ($notificationEnabled == null ? 43 : $notificationEnabled.hashCode());
        final java.lang.Object $locationSharingEnabled = this.getLocationSharingEnabled();
        result = result * PRIME + ($locationSharingEnabled == null ? 43 : $locationSharingEnabled.hashCode());
        final java.lang.Object $privacyModeEnabled = this.getPrivacyModeEnabled();
        result = result * PRIME + ($privacyModeEnabled == null ? 43 : $privacyModeEnabled.hashCode());
        final java.lang.Object $fullName = this.getFullName();
        result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        final java.lang.Object $dateOfBirth = this.getDateOfBirth();
        result = result * PRIME + ($dateOfBirth == null ? 43 : $dateOfBirth.hashCode());
        final java.lang.Object $gender = this.getGender();
        result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $country = this.getCountry();
        result = result * PRIME + ($country == null ? 43 : $country.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "UpdateProfileRequest(fullName=" + this.getFullName() + ", email=" + this.getEmail() + ", phoneNumber=" + this.getPhoneNumber() + ", dateOfBirth=" + this.getDateOfBirth() + ", gender=" + this.getGender() + ", address=" + this.getAddress() + ", city=" + this.getCity() + ", state=" + this.getState() + ", country=" + this.getCountry() + ", homeLatitude=" + this.getHomeLatitude() + ", homeLongitude=" + this.getHomeLongitude() + ", workLatitude=" + this.getWorkLatitude() + ", workLongitude=" + this.getWorkLongitude() + ", notificationEnabled=" + this.getNotificationEnabled() + ", locationSharingEnabled=" + this.getLocationSharingEnabled() + ", privacyModeEnabled=" + this.getPrivacyModeEnabled() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public UpdateProfileRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public UpdateProfileRequest(final String fullName, final String email, final String phoneNumber, final String dateOfBirth, final String gender, final String address, final String city, final String state, final String country, final Double homeLatitude, final Double homeLongitude, final Double workLatitude, final Double workLongitude, final Boolean notificationEnabled, final Boolean locationSharingEnabled, final Boolean privacyModeEnabled) {
        this.fullName = fullName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.address = address;
        this.city = city;
        this.state = state;
        this.country = country;
        this.homeLatitude = homeLatitude;
        this.homeLongitude = homeLongitude;
        this.workLatitude = workLatitude;
        this.workLongitude = workLongitude;
        this.notificationEnabled = notificationEnabled;
        this.locationSharingEnabled = locationSharingEnabled;
        this.privacyModeEnabled = privacyModeEnabled;
    }
}
