// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.dto;

public class UserProfileDto {
    private Long id;
    private Long userId;
    private String avatarUrl;
    private String bloodGroup;
    private String medicalNotes;
    private String address;
    private Double homeLat;
    private Double homeLng;


    @java.lang.SuppressWarnings("all")
    public static class UserProfileDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String avatarUrl;
        @java.lang.SuppressWarnings("all")
        private String bloodGroup;
        @java.lang.SuppressWarnings("all")
        private String medicalNotes;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private Double homeLat;
        @java.lang.SuppressWarnings("all")
        private Double homeLng;

        @java.lang.SuppressWarnings("all")
        UserProfileDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder avatarUrl(final String avatarUrl) {
            this.avatarUrl = avatarUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder bloodGroup(final String bloodGroup) {
            this.bloodGroup = bloodGroup;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder medicalNotes(final String medicalNotes) {
            this.medicalNotes = medicalNotes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder homeLat(final Double homeLat) {
            this.homeLat = homeLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfileDto.UserProfileDtoBuilder homeLng(final Double homeLng) {
            this.homeLng = homeLng;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public UserProfileDto build() {
            return new UserProfileDto(this.id, this.userId, this.avatarUrl, this.bloodGroup, this.medicalNotes, this.address, this.homeLat, this.homeLng);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "UserProfileDto.UserProfileDtoBuilder(id=" + this.id + ", userId=" + this.userId + ", avatarUrl=" + this.avatarUrl + ", bloodGroup=" + this.bloodGroup + ", medicalNotes=" + this.medicalNotes + ", address=" + this.address + ", homeLat=" + this.homeLat + ", homeLng=" + this.homeLng + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static UserProfileDto.UserProfileDtoBuilder builder() {
        return new UserProfileDto.UserProfileDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getBloodGroup() {
        return this.bloodGroup;
    }

    @java.lang.SuppressWarnings("all")
    public String getMedicalNotes() {
        return this.medicalNotes;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public Double getHomeLat() {
        return this.homeLat;
    }

    @java.lang.SuppressWarnings("all")
    public Double getHomeLng() {
        return this.homeLng;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvatarUrl(final String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setBloodGroup(final String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicalNotes(final String medicalNotes) {
        this.medicalNotes = medicalNotes;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setHomeLat(final Double homeLat) {
        this.homeLat = homeLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setHomeLng(final Double homeLng) {
        this.homeLng = homeLng;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserProfileDto)) return false;
        final UserProfileDto other = (UserProfileDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$homeLat = this.getHomeLat();
        final java.lang.Object other$homeLat = other.getHomeLat();
        if (this$homeLat == null ? other$homeLat != null : !this$homeLat.equals(other$homeLat)) return false;
        final java.lang.Object this$homeLng = this.getHomeLng();
        final java.lang.Object other$homeLng = other.getHomeLng();
        if (this$homeLng == null ? other$homeLng != null : !this$homeLng.equals(other$homeLng)) return false;
        final java.lang.Object this$avatarUrl = this.getAvatarUrl();
        final java.lang.Object other$avatarUrl = other.getAvatarUrl();
        if (this$avatarUrl == null ? other$avatarUrl != null : !this$avatarUrl.equals(other$avatarUrl)) return false;
        final java.lang.Object this$bloodGroup = this.getBloodGroup();
        final java.lang.Object other$bloodGroup = other.getBloodGroup();
        if (this$bloodGroup == null ? other$bloodGroup != null : !this$bloodGroup.equals(other$bloodGroup)) return false;
        final java.lang.Object this$medicalNotes = this.getMedicalNotes();
        final java.lang.Object other$medicalNotes = other.getMedicalNotes();
        if (this$medicalNotes == null ? other$medicalNotes != null : !this$medicalNotes.equals(other$medicalNotes)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserProfileDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $homeLat = this.getHomeLat();
        result = result * PRIME + ($homeLat == null ? 43 : $homeLat.hashCode());
        final java.lang.Object $homeLng = this.getHomeLng();
        result = result * PRIME + ($homeLng == null ? 43 : $homeLng.hashCode());
        final java.lang.Object $avatarUrl = this.getAvatarUrl();
        result = result * PRIME + ($avatarUrl == null ? 43 : $avatarUrl.hashCode());
        final java.lang.Object $bloodGroup = this.getBloodGroup();
        result = result * PRIME + ($bloodGroup == null ? 43 : $bloodGroup.hashCode());
        final java.lang.Object $medicalNotes = this.getMedicalNotes();
        result = result * PRIME + ($medicalNotes == null ? 43 : $medicalNotes.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "UserProfileDto(id=" + this.getId() + ", userId=" + this.getUserId() + ", avatarUrl=" + this.getAvatarUrl() + ", bloodGroup=" + this.getBloodGroup() + ", medicalNotes=" + this.getMedicalNotes() + ", address=" + this.getAddress() + ", homeLat=" + this.getHomeLat() + ", homeLng=" + this.getHomeLng() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public UserProfileDto() {
    }

    @java.lang.SuppressWarnings("all")
    public UserProfileDto(final Long id, final Long userId, final String avatarUrl, final String bloodGroup, final String medicalNotes, final String address, final Double homeLat, final Double homeLng) {
        this.id = id;
        this.userId = userId;
        this.avatarUrl = avatarUrl;
        this.bloodGroup = bloodGroup;
        this.medicalNotes = medicalNotes;
        this.address = address;
        this.homeLat = homeLat;
        this.homeLng = homeLng;
    }
}
