// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.dto;

public class UserPreferenceDto {
    private Long id;
    private Long userId;
    private boolean enableSmsAlerts;
    private boolean enableEmailAlerts;
    private boolean enablePushNotifications;
    private boolean shareLiveLocationWithContacts;
    private boolean autoTriggerPoliceCallOnSos;
    private String preferredMapTheme;


    @java.lang.SuppressWarnings("all")
    public static class UserPreferenceDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private boolean enableSmsAlerts;
        @java.lang.SuppressWarnings("all")
        private boolean enableEmailAlerts;
        @java.lang.SuppressWarnings("all")
        private boolean enablePushNotifications;
        @java.lang.SuppressWarnings("all")
        private boolean shareLiveLocationWithContacts;
        @java.lang.SuppressWarnings("all")
        private boolean autoTriggerPoliceCallOnSos;
        @java.lang.SuppressWarnings("all")
        private String preferredMapTheme;

        @java.lang.SuppressWarnings("all")
        UserPreferenceDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder enableSmsAlerts(final boolean enableSmsAlerts) {
            this.enableSmsAlerts = enableSmsAlerts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder enableEmailAlerts(final boolean enableEmailAlerts) {
            this.enableEmailAlerts = enableEmailAlerts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder enablePushNotifications(final boolean enablePushNotifications) {
            this.enablePushNotifications = enablePushNotifications;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder shareLiveLocationWithContacts(final boolean shareLiveLocationWithContacts) {
            this.shareLiveLocationWithContacts = shareLiveLocationWithContacts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder autoTriggerPoliceCallOnSos(final boolean autoTriggerPoliceCallOnSos) {
            this.autoTriggerPoliceCallOnSos = autoTriggerPoliceCallOnSos;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto.UserPreferenceDtoBuilder preferredMapTheme(final String preferredMapTheme) {
            this.preferredMapTheme = preferredMapTheme;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public UserPreferenceDto build() {
            return new UserPreferenceDto(this.id, this.userId, this.enableSmsAlerts, this.enableEmailAlerts, this.enablePushNotifications, this.shareLiveLocationWithContacts, this.autoTriggerPoliceCallOnSos, this.preferredMapTheme);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "UserPreferenceDto.UserPreferenceDtoBuilder(id=" + this.id + ", userId=" + this.userId + ", enableSmsAlerts=" + this.enableSmsAlerts + ", enableEmailAlerts=" + this.enableEmailAlerts + ", enablePushNotifications=" + this.enablePushNotifications + ", shareLiveLocationWithContacts=" + this.shareLiveLocationWithContacts + ", autoTriggerPoliceCallOnSos=" + this.autoTriggerPoliceCallOnSos + ", preferredMapTheme=" + this.preferredMapTheme + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static UserPreferenceDto.UserPreferenceDtoBuilder builder() {
        return new UserPreferenceDto.UserPreferenceDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEnableSmsAlerts() {
        return this.enableSmsAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEnableEmailAlerts() {
        return this.enableEmailAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEnablePushNotifications() {
        return this.enablePushNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isShareLiveLocationWithContacts() {
        return this.shareLiveLocationWithContacts;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAutoTriggerPoliceCallOnSos() {
        return this.autoTriggerPoliceCallOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreferredMapTheme() {
        return this.preferredMapTheme;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnableSmsAlerts(final boolean enableSmsAlerts) {
        this.enableSmsAlerts = enableSmsAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnableEmailAlerts(final boolean enableEmailAlerts) {
        this.enableEmailAlerts = enableEmailAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnablePushNotifications(final boolean enablePushNotifications) {
        this.enablePushNotifications = enablePushNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setShareLiveLocationWithContacts(final boolean shareLiveLocationWithContacts) {
        this.shareLiveLocationWithContacts = shareLiveLocationWithContacts;
    }

    @java.lang.SuppressWarnings("all")
    public void setAutoTriggerPoliceCallOnSos(final boolean autoTriggerPoliceCallOnSos) {
        this.autoTriggerPoliceCallOnSos = autoTriggerPoliceCallOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreferredMapTheme(final String preferredMapTheme) {
        this.preferredMapTheme = preferredMapTheme;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserPreferenceDto)) return false;
        final UserPreferenceDto other = (UserPreferenceDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isEnableSmsAlerts() != other.isEnableSmsAlerts()) return false;
        if (this.isEnableEmailAlerts() != other.isEnableEmailAlerts()) return false;
        if (this.isEnablePushNotifications() != other.isEnablePushNotifications()) return false;
        if (this.isShareLiveLocationWithContacts() != other.isShareLiveLocationWithContacts()) return false;
        if (this.isAutoTriggerPoliceCallOnSos() != other.isAutoTriggerPoliceCallOnSos()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$preferredMapTheme = this.getPreferredMapTheme();
        final java.lang.Object other$preferredMapTheme = other.getPreferredMapTheme();
        if (this$preferredMapTheme == null ? other$preferredMapTheme != null : !this$preferredMapTheme.equals(other$preferredMapTheme)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserPreferenceDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isEnableSmsAlerts() ? 79 : 97);
        result = result * PRIME + (this.isEnableEmailAlerts() ? 79 : 97);
        result = result * PRIME + (this.isEnablePushNotifications() ? 79 : 97);
        result = result * PRIME + (this.isShareLiveLocationWithContacts() ? 79 : 97);
        result = result * PRIME + (this.isAutoTriggerPoliceCallOnSos() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $preferredMapTheme = this.getPreferredMapTheme();
        result = result * PRIME + ($preferredMapTheme == null ? 43 : $preferredMapTheme.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "UserPreferenceDto(id=" + this.getId() + ", userId=" + this.getUserId() + ", enableSmsAlerts=" + this.isEnableSmsAlerts() + ", enableEmailAlerts=" + this.isEnableEmailAlerts() + ", enablePushNotifications=" + this.isEnablePushNotifications() + ", shareLiveLocationWithContacts=" + this.isShareLiveLocationWithContacts() + ", autoTriggerPoliceCallOnSos=" + this.isAutoTriggerPoliceCallOnSos() + ", preferredMapTheme=" + this.getPreferredMapTheme() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public UserPreferenceDto() {
    }

    @java.lang.SuppressWarnings("all")
    public UserPreferenceDto(final Long id, final Long userId, final boolean enableSmsAlerts, final boolean enableEmailAlerts, final boolean enablePushNotifications, final boolean shareLiveLocationWithContacts, final boolean autoTriggerPoliceCallOnSos, final String preferredMapTheme) {
        this.id = id;
        this.userId = userId;
        this.enableSmsAlerts = enableSmsAlerts;
        this.enableEmailAlerts = enableEmailAlerts;
        this.enablePushNotifications = enablePushNotifications;
        this.shareLiveLocationWithContacts = shareLiveLocationWithContacts;
        this.autoTriggerPoliceCallOnSos = autoTriggerPoliceCallOnSos;
        this.preferredMapTheme = preferredMapTheme;
    }
}
