// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.entity;

import com.velora.ai.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "ai_chat_history")
public class AiChatHistory extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Long userId;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String userQuery;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String aiResponse;
    @Column(length = 50)
    private String category; // EMERGENCY_ADVICE, SAFE_ROUTE, GENERAL_SAFETY


    @java.lang.SuppressWarnings("all")
    public static class AiChatHistoryBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String userQuery;
        @java.lang.SuppressWarnings("all")
        private String aiResponse;
        @java.lang.SuppressWarnings("all")
        private String category;

        @java.lang.SuppressWarnings("all")
        AiChatHistoryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatHistory.AiChatHistoryBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatHistory.AiChatHistoryBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatHistory.AiChatHistoryBuilder userQuery(final String userQuery) {
            this.userQuery = userQuery;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatHistory.AiChatHistoryBuilder aiResponse(final String aiResponse) {
            this.aiResponse = aiResponse;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatHistory.AiChatHistoryBuilder category(final String category) {
            this.category = category;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public AiChatHistory build() {
            return new AiChatHistory(this.id, this.userId, this.userQuery, this.aiResponse, this.category);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AiChatHistory.AiChatHistoryBuilder(id=" + this.id + ", userId=" + this.userId + ", userQuery=" + this.userQuery + ", aiResponse=" + this.aiResponse + ", category=" + this.category + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static AiChatHistory.AiChatHistoryBuilder builder() {
        return new AiChatHistory.AiChatHistoryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserQuery() {
        return this.userQuery;
    }

    @java.lang.SuppressWarnings("all")
    public String getAiResponse() {
        return this.aiResponse;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserQuery(final String userQuery) {
        this.userQuery = userQuery;
    }

    @java.lang.SuppressWarnings("all")
    public void setAiResponse(final String aiResponse) {
        this.aiResponse = aiResponse;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    public AiChatHistory() {
    }

    @java.lang.SuppressWarnings("all")
    public AiChatHistory(final Long id, final Long userId, final String userQuery, final String aiResponse, final String category) {
        this.id = id;
        this.userId = userId;
        this.userQuery = userQuery;
        this.aiResponse = aiResponse;
        this.category = category;
    }
}
