// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.entity;

import com.velora.ai.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "risk_predictions")
public class RiskPrediction extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Double latitude;
    @Column(nullable = false)
    private Double longitude;
    @Column(nullable = false)
    private Double riskScore; // 0.0 (Safe) to 100.0 (Extremely High Risk)
    @Column(nullable = false, length = 50)
    private String riskLevel; // LOW, MODERATE, HIGH, SEVERE
    @Column(columnDefinition = "TEXT")
    private String riskFactors;


    @java.lang.SuppressWarnings("all")
    public static class RiskPredictionBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private Double riskScore;
        @java.lang.SuppressWarnings("all")
        private String riskLevel;
        @java.lang.SuppressWarnings("all")
        private String riskFactors;

        @java.lang.SuppressWarnings("all")
        RiskPredictionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPrediction.RiskPredictionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPrediction.RiskPredictionBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPrediction.RiskPredictionBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPrediction.RiskPredictionBuilder riskScore(final Double riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPrediction.RiskPredictionBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPrediction.RiskPredictionBuilder riskFactors(final String riskFactors) {
            this.riskFactors = riskFactors;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RiskPrediction build() {
            return new RiskPrediction(this.id, this.latitude, this.longitude, this.riskScore, this.riskLevel, this.riskFactors);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RiskPrediction.RiskPredictionBuilder(id=" + this.id + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", riskScore=" + this.riskScore + ", riskLevel=" + this.riskLevel + ", riskFactors=" + this.riskFactors + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RiskPrediction.RiskPredictionBuilder builder() {
        return new RiskPrediction.RiskPredictionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getRiskScore() {
        return this.riskScore;
    }

    @java.lang.SuppressWarnings("all")
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    public String getRiskFactors() {
        return this.riskFactors;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskScore(final Double riskScore) {
        this.riskScore = riskScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskFactors(final String riskFactors) {
        this.riskFactors = riskFactors;
    }

    @java.lang.SuppressWarnings("all")
    public RiskPrediction() {
    }

    @java.lang.SuppressWarnings("all")
    public RiskPrediction(final Long id, final Double latitude, final Double longitude, final Double riskScore, final String riskLevel, final String riskFactors) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.riskScore = riskScore;
        this.riskLevel = riskLevel;
        this.riskFactors = riskFactors;
    }
}
