// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.entity;

import com.velora.safety.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "risk_zones")
public class RiskZone extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, length = 150)
    private String zoneName;
    @Column(nullable = false)
    private Double centerLat;
    @Column(nullable = false)
    private Double centerLng;
    @Column(nullable = false)
    private Double radiusMeters;
    @Column(nullable = false)
    private Double riskLevelScore; // 0.0 (Safe) to 100.0 (Extremely High Risk)
    @Column(columnDefinition = "TEXT")
    private String description;


    @java.lang.SuppressWarnings("all")
    public static class RiskZoneBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String zoneName;
        @java.lang.SuppressWarnings("all")
        private Double centerLat;
        @java.lang.SuppressWarnings("all")
        private Double centerLng;
        @java.lang.SuppressWarnings("all")
        private Double radiusMeters;
        @java.lang.SuppressWarnings("all")
        private Double riskLevelScore;
        @java.lang.SuppressWarnings("all")
        private String description;

        @java.lang.SuppressWarnings("all")
        RiskZoneBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder zoneName(final String zoneName) {
            this.zoneName = zoneName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder centerLat(final Double centerLat) {
            this.centerLat = centerLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder centerLng(final Double centerLng) {
            this.centerLng = centerLng;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder radiusMeters(final Double radiusMeters) {
            this.radiusMeters = radiusMeters;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder riskLevelScore(final Double riskLevelScore) {
            this.riskLevelScore = riskLevelScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskZone.RiskZoneBuilder description(final String description) {
            this.description = description;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RiskZone build() {
            return new RiskZone(this.id, this.zoneName, this.centerLat, this.centerLng, this.radiusMeters, this.riskLevelScore, this.description);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RiskZone.RiskZoneBuilder(id=" + this.id + ", zoneName=" + this.zoneName + ", centerLat=" + this.centerLat + ", centerLng=" + this.centerLng + ", radiusMeters=" + this.radiusMeters + ", riskLevelScore=" + this.riskLevelScore + ", description=" + this.description + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RiskZone.RiskZoneBuilder builder() {
        return new RiskZone.RiskZoneBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getZoneName() {
        return this.zoneName;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCenterLat() {
        return this.centerLat;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCenterLng() {
        return this.centerLng;
    }

    @java.lang.SuppressWarnings("all")
    public Double getRadiusMeters() {
        return this.radiusMeters;
    }

    @java.lang.SuppressWarnings("all")
    public Double getRiskLevelScore() {
        return this.riskLevelScore;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setZoneName(final String zoneName) {
        this.zoneName = zoneName;
    }

    @java.lang.SuppressWarnings("all")
    public void setCenterLat(final Double centerLat) {
        this.centerLat = centerLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setCenterLng(final Double centerLng) {
        this.centerLng = centerLng;
    }

    @java.lang.SuppressWarnings("all")
    public void setRadiusMeters(final Double radiusMeters) {
        this.radiusMeters = radiusMeters;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskLevelScore(final Double riskLevelScore) {
        this.riskLevelScore = riskLevelScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public RiskZone() {
    }

    @java.lang.SuppressWarnings("all")
    public RiskZone(final Long id, final String zoneName, final Double centerLat, final Double centerLng, final Double radiusMeters, final Double riskLevelScore, final String description) {
        this.id = id;
        this.zoneName = zoneName;
        this.centerLat = centerLat;
        this.centerLng = centerLng;
        this.radiusMeters = radiusMeters;
        this.riskLevelScore = riskLevelScore;
        this.description = description;
    }
}
