// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.entity;

import com.velora.safety.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "route_history")
public class RouteHistory extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Long userId;
    private Double originLat;
    private Double originLng;
    private Double destinationLat;
    private Double destinationLng;
    private Double calculatedRiskScore;
    private String selectedRouteType; // SAFEST, FASTEST


    @java.lang.SuppressWarnings("all")
    public static class RouteHistoryBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private Double originLat;
        @java.lang.SuppressWarnings("all")
        private Double originLng;
        @java.lang.SuppressWarnings("all")
        private Double destinationLat;
        @java.lang.SuppressWarnings("all")
        private Double destinationLng;
        @java.lang.SuppressWarnings("all")
        private Double calculatedRiskScore;
        @java.lang.SuppressWarnings("all")
        private String selectedRouteType;

        @java.lang.SuppressWarnings("all")
        RouteHistoryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder originLat(final Double originLat) {
            this.originLat = originLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder originLng(final Double originLng) {
            this.originLng = originLng;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder destinationLat(final Double destinationLat) {
            this.destinationLat = destinationLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder destinationLng(final Double destinationLng) {
            this.destinationLng = destinationLng;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder calculatedRiskScore(final Double calculatedRiskScore) {
            this.calculatedRiskScore = calculatedRiskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteHistory.RouteHistoryBuilder selectedRouteType(final String selectedRouteType) {
            this.selectedRouteType = selectedRouteType;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RouteHistory build() {
            return new RouteHistory(this.id, this.userId, this.originLat, this.originLng, this.destinationLat, this.destinationLng, this.calculatedRiskScore, this.selectedRouteType);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RouteHistory.RouteHistoryBuilder(id=" + this.id + ", userId=" + this.userId + ", originLat=" + this.originLat + ", originLng=" + this.originLng + ", destinationLat=" + this.destinationLat + ", destinationLng=" + this.destinationLng + ", calculatedRiskScore=" + this.calculatedRiskScore + ", selectedRouteType=" + this.selectedRouteType + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RouteHistory.RouteHistoryBuilder builder() {
        return new RouteHistory.RouteHistoryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public Double getOriginLat() {
        return this.originLat;
    }

    @java.lang.SuppressWarnings("all")
    public Double getOriginLng() {
        return this.originLng;
    }

    @java.lang.SuppressWarnings("all")
    public Double getDestinationLat() {
        return this.destinationLat;
    }

    @java.lang.SuppressWarnings("all")
    public Double getDestinationLng() {
        return this.destinationLng;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCalculatedRiskScore() {
        return this.calculatedRiskScore;
    }

    @java.lang.SuppressWarnings("all")
    public String getSelectedRouteType() {
        return this.selectedRouteType;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setOriginLat(final Double originLat) {
        this.originLat = originLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setOriginLng(final Double originLng) {
        this.originLng = originLng;
    }

    @java.lang.SuppressWarnings("all")
    public void setDestinationLat(final Double destinationLat) {
        this.destinationLat = destinationLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setDestinationLng(final Double destinationLng) {
        this.destinationLng = destinationLng;
    }

    @java.lang.SuppressWarnings("all")
    public void setCalculatedRiskScore(final Double calculatedRiskScore) {
        this.calculatedRiskScore = calculatedRiskScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setSelectedRouteType(final String selectedRouteType) {
        this.selectedRouteType = selectedRouteType;
    }

    @java.lang.SuppressWarnings("all")
    public RouteHistory() {
    }

    @java.lang.SuppressWarnings("all")
    public RouteHistory(final Long id, final Long userId, final Double originLat, final Double originLng, final Double destinationLat, final Double destinationLng, final Double calculatedRiskScore, final String selectedRouteType) {
        this.id = id;
        this.userId = userId;
        this.originLat = originLat;
        this.originLng = originLng;
        this.destinationLat = destinationLat;
        this.destinationLng = destinationLng;
        this.calculatedRiskScore = calculatedRiskScore;
        this.selectedRouteType = selectedRouteType;
    }
}
