// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.entity;

import com.velora.safety.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "safe_zones", indexes = {@Index(name = "idx_safe_zones_type", columnList = "zone_type"), @Index(name = "idx_safe_zones_location", columnList = "latitude, longitude"), @Index(name = "idx_safe_zones_city", columnList = "city")})
public class SafeZone extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "name", nullable = false, length = 200)
    private String name;
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    @Column(name = "zone_type", nullable = false, length = 50)
    @Enumerated(EnumType.STRING)
    private ZoneType zoneType;
    @Column(name = "latitude", nullable = false)
    private Double latitude;
    @Column(name = "longitude", nullable = false)
    private Double longitude;
    @Column(name = "radius_meters")
    private Double radiusMeters;
    @Column(name = "address", length = 500)
    private String address;
    @Column(name = "city", length = 100)
    private String city;
    @Column(name = "state", length = 100)
    private String state;
    @Column(name = "phone_number", length = 20)
    private String phoneNumber;
    @Column(name = "is_verified", nullable = false)
    private boolean verified;
    @Column(name = "is_active", nullable = false)
    private boolean active;
    @Column(name = "safety_score")
    private Integer safetyScore;


    public enum ZoneType {
        POLICE_STATION, HOSPITAL, FIRE_STATION, SAFE_HOUSE, PUBLIC_SHELTER, WOMEN_CENTER, COMMUNITY_CENTER, SCHOOL, GOVERNMENT_OFFICE, OTHER;
    }

    @java.lang.SuppressWarnings("all")
    private static Double $default$radiusMeters() {
        return 200.0;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$verified() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$active() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static Integer $default$safetyScore() {
        return 80;
    }


    @java.lang.SuppressWarnings("all")
    public static class SafeZoneBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String description;
        @java.lang.SuppressWarnings("all")
        private ZoneType zoneType;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private boolean radiusMeters$set;
        @java.lang.SuppressWarnings("all")
        private Double radiusMeters$value;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private String city;
        @java.lang.SuppressWarnings("all")
        private String state;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private boolean verified$set;
        @java.lang.SuppressWarnings("all")
        private boolean verified$value;
        @java.lang.SuppressWarnings("all")
        private boolean active$set;
        @java.lang.SuppressWarnings("all")
        private boolean active$value;
        @java.lang.SuppressWarnings("all")
        private boolean safetyScore$set;
        @java.lang.SuppressWarnings("all")
        private Integer safetyScore$value;

        @java.lang.SuppressWarnings("all")
        SafeZoneBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder zoneType(final ZoneType zoneType) {
            this.zoneType = zoneType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder radiusMeters(final Double radiusMeters) {
            this.radiusMeters$value = radiusMeters;
            radiusMeters$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder state(final String state) {
            this.state = state;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder verified(final boolean verified) {
            this.verified$value = verified;
            verified$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder active(final boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZone.SafeZoneBuilder safetyScore(final Integer safetyScore) {
            this.safetyScore$value = safetyScore;
            safetyScore$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SafeZone build() {
            Double radiusMeters$value = this.radiusMeters$value;
            if (!this.radiusMeters$set) radiusMeters$value = SafeZone.$default$radiusMeters();
            boolean verified$value = this.verified$value;
            if (!this.verified$set) verified$value = SafeZone.$default$verified();
            boolean active$value = this.active$value;
            if (!this.active$set) active$value = SafeZone.$default$active();
            Integer safetyScore$value = this.safetyScore$value;
            if (!this.safetyScore$set) safetyScore$value = SafeZone.$default$safetyScore();
            return new SafeZone(this.id, this.name, this.description, this.zoneType, this.latitude, this.longitude, radiusMeters$value, this.address, this.city, this.state, this.phoneNumber, verified$value, active$value, safetyScore$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SafeZone.SafeZoneBuilder(id=" + this.id + ", name=" + this.name + ", description=" + this.description + ", zoneType=" + this.zoneType + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", radiusMeters$value=" + this.radiusMeters$value + ", address=" + this.address + ", city=" + this.city + ", state=" + this.state + ", phoneNumber=" + this.phoneNumber + ", verified$value=" + this.verified$value + ", active$value=" + this.active$value + ", safetyScore$value=" + this.safetyScore$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SafeZone.SafeZoneBuilder builder() {
        return new SafeZone.SafeZoneBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public ZoneType getZoneType() {
        return this.zoneType;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getRadiusMeters() {
        return this.radiusMeters;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isVerified() {
        return this.verified;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSafetyScore() {
        return this.safetyScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setZoneType(final ZoneType zoneType) {
        this.zoneType = zoneType;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setRadiusMeters(final Double radiusMeters) {
        this.radiusMeters = radiusMeters;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setVerified(final boolean verified) {
        this.verified = verified;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyScore(final Integer safetyScore) {
        this.safetyScore = safetyScore;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SafeZone)) return false;
        final SafeZone other = (SafeZone) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isVerified() != other.isVerified()) return false;
        if (this.isActive() != other.isActive()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$radiusMeters = this.getRadiusMeters();
        final java.lang.Object other$radiusMeters = other.getRadiusMeters();
        if (this$radiusMeters == null ? other$radiusMeters != null : !this$radiusMeters.equals(other$radiusMeters)) return false;
        final java.lang.Object this$safetyScore = this.getSafetyScore();
        final java.lang.Object other$safetyScore = other.getSafetyScore();
        if (this$safetyScore == null ? other$safetyScore != null : !this$safetyScore.equals(other$safetyScore)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$zoneType = this.getZoneType();
        final java.lang.Object other$zoneType = other.getZoneType();
        if (this$zoneType == null ? other$zoneType != null : !this$zoneType.equals(other$zoneType)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SafeZone;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isVerified() ? 79 : 97);
        result = result * PRIME + (this.isActive() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $radiusMeters = this.getRadiusMeters();
        result = result * PRIME + ($radiusMeters == null ? 43 : $radiusMeters.hashCode());
        final java.lang.Object $safetyScore = this.getSafetyScore();
        result = result * PRIME + ($safetyScore == null ? 43 : $safetyScore.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $zoneType = this.getZoneType();
        result = result * PRIME + ($zoneType == null ? 43 : $zoneType.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SafeZone(id=" + this.getId() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", zoneType=" + this.getZoneType() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", radiusMeters=" + this.getRadiusMeters() + ", address=" + this.getAddress() + ", city=" + this.getCity() + ", state=" + this.getState() + ", phoneNumber=" + this.getPhoneNumber() + ", verified=" + this.isVerified() + ", active=" + this.isActive() + ", safetyScore=" + this.getSafetyScore() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SafeZone() {
        this.radiusMeters = SafeZone.$default$radiusMeters();
        this.verified = SafeZone.$default$verified();
        this.active = SafeZone.$default$active();
        this.safetyScore = SafeZone.$default$safetyScore();
    }

    @java.lang.SuppressWarnings("all")
    public SafeZone(final Long id, final String name, final String description, final ZoneType zoneType, final Double latitude, final Double longitude, final Double radiusMeters, final String address, final String city, final String state, final String phoneNumber, final boolean verified, final boolean active, final Integer safetyScore) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.zoneType = zoneType;
        this.latitude = latitude;
        this.longitude = longitude;
        this.radiusMeters = radiusMeters;
        this.address = address;
        this.city = city;
        this.state = state;
        this.phoneNumber = phoneNumber;
        this.verified = verified;
        this.active = active;
        this.safetyScore = safetyScore;
    }
}
