// Generated by delombok at Wed Aug 05 15:39:30 IST 2026
package com.velora.police.entity;

import com.velora.police.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "assignments")
public class Assignment extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Long sosAlertId;
    @Column(nullable = false)
    private Long policeUnitId;
    @Column(nullable = false, length = 50)
    private String status = "DISPATCHED"; // DISPATCHED, ON_SCENE, COMPLETED


    @java.lang.SuppressWarnings("all")
    public static class AssignmentBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long sosAlertId;
        @java.lang.SuppressWarnings("all")
        private Long policeUnitId;
        @java.lang.SuppressWarnings("all")
        private String status;

        @java.lang.SuppressWarnings("all")
        AssignmentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Assignment.AssignmentBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Assignment.AssignmentBuilder sosAlertId(final Long sosAlertId) {
            this.sosAlertId = sosAlertId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Assignment.AssignmentBuilder policeUnitId(final Long policeUnitId) {
            this.policeUnitId = policeUnitId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Assignment.AssignmentBuilder status(final String status) {
            this.status = status;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Assignment build() {
            return new Assignment(this.id, this.sosAlertId, this.policeUnitId, this.status);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Assignment.AssignmentBuilder(id=" + this.id + ", sosAlertId=" + this.sosAlertId + ", policeUnitId=" + this.policeUnitId + ", status=" + this.status + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Assignment.AssignmentBuilder builder() {
        return new Assignment.AssignmentBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSosAlertId() {
        return this.sosAlertId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getPoliceUnitId() {
        return this.policeUnitId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSosAlertId(final Long sosAlertId) {
        this.sosAlertId = sosAlertId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPoliceUnitId(final Long policeUnitId) {
        this.policeUnitId = policeUnitId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public Assignment() {
    }

    @java.lang.SuppressWarnings("all")
    public Assignment(final Long id, final Long sosAlertId, final Long policeUnitId, final String status) {
        this.id = id;
        this.sosAlertId = sosAlertId;
        this.policeUnitId = policeUnitId;
        this.status = status;
    }
}
