// Generated by delombok at Wed Aug 05 15:39:30 IST 2026
package com.velora.police.entity;

import com.velora.police.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "police_units")
public class PoliceUnit extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true)
    private Long userId;
    @Column(nullable = false, length = 100)
    private String stationName;
    @Column(nullable = false, length = 50)
    private String badgeNumber;
    @Column(nullable = false, length = 20)
    private String emergencyHotline;
    private Double currentLat;
    private Double currentLng;
    @Column(nullable = false)
    private boolean isAvailable = true;


    @java.lang.SuppressWarnings("all")
    public static class PoliceUnitBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String stationName;
        @java.lang.SuppressWarnings("all")
        private String badgeNumber;
        @java.lang.SuppressWarnings("all")
        private String emergencyHotline;
        @java.lang.SuppressWarnings("all")
        private Double currentLat;
        @java.lang.SuppressWarnings("all")
        private Double currentLng;
        @java.lang.SuppressWarnings("all")
        private boolean isAvailable;

        @java.lang.SuppressWarnings("all")
        PoliceUnitBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder stationName(final String stationName) {
            this.stationName = stationName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder badgeNumber(final String badgeNumber) {
            this.badgeNumber = badgeNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder emergencyHotline(final String emergencyHotline) {
            this.emergencyHotline = emergencyHotline;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder currentLat(final Double currentLat) {
            this.currentLat = currentLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder currentLng(final Double currentLng) {
            this.currentLng = currentLng;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnit.PoliceUnitBuilder isAvailable(final boolean isAvailable) {
            this.isAvailable = isAvailable;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PoliceUnit build() {
            return new PoliceUnit(this.id, this.userId, this.stationName, this.badgeNumber, this.emergencyHotline, this.currentLat, this.currentLng, this.isAvailable);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PoliceUnit.PoliceUnitBuilder(id=" + this.id + ", userId=" + this.userId + ", stationName=" + this.stationName + ", badgeNumber=" + this.badgeNumber + ", emergencyHotline=" + this.emergencyHotline + ", currentLat=" + this.currentLat + ", currentLng=" + this.currentLng + ", isAvailable=" + this.isAvailable + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PoliceUnit.PoliceUnitBuilder builder() {
        return new PoliceUnit.PoliceUnitBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStationName() {
        return this.stationName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBadgeNumber() {
        return this.badgeNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmergencyHotline() {
        return this.emergencyHotline;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCurrentLat() {
        return this.currentLat;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCurrentLng() {
        return this.currentLng;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAvailable() {
        return this.isAvailable;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStationName(final String stationName) {
        this.stationName = stationName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBadgeNumber(final String badgeNumber) {
        this.badgeNumber = badgeNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmergencyHotline(final String emergencyHotline) {
        this.emergencyHotline = emergencyHotline;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentLat(final Double currentLat) {
        this.currentLat = currentLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentLng(final Double currentLng) {
        this.currentLng = currentLng;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvailable(final boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    @java.lang.SuppressWarnings("all")
    public PoliceUnit() {
    }

    @java.lang.SuppressWarnings("all")
    public PoliceUnit(final Long id, final Long userId, final String stationName, final String badgeNumber, final String emergencyHotline, final Double currentLat, final Double currentLng, final boolean isAvailable) {
        this.id = id;
        this.userId = userId;
        this.stationName = stationName;
        this.badgeNumber = badgeNumber;
        this.emergencyHotline = emergencyHotline;
        this.currentLat = currentLat;
        this.currentLng = currentLng;
        this.isAvailable = isAvailable;
    }
}
