// Generated by delombok at Wed Aug 05 15:39:30 IST 2026
package com.velora.police.entity;

import com.velora.police.common.BaseAuditableEntity;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "sos_alerts", indexes = {@Index(name = "idx_sos_status", columnList = "status")})
public class SosAlert extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Long userId;
    @Column(nullable = false)
    private Double latitude;
    @Column(nullable = false)
    private Double longitude;
    @Column(nullable = false, length = 50)
    private String status = "ACTIVE"; // ACTIVE, ACKNOWLEDGED, DISPATCHED, RESOLVED, FALSE_ALARM
    private Long assignedPoliceId;
    private LocalDateTime resolvedAt;


    @java.lang.SuppressWarnings("all")
    public static class SosAlertBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private String status;
        @java.lang.SuppressWarnings("all")
        private Long assignedPoliceId;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime resolvedAt;

        @java.lang.SuppressWarnings("all")
        SosAlertBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder assignedPoliceId(final Long assignedPoliceId) {
            this.assignedPoliceId = assignedPoliceId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlert.SosAlertBuilder resolvedAt(final LocalDateTime resolvedAt) {
            this.resolvedAt = resolvedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SosAlert build() {
            return new SosAlert(this.id, this.userId, this.latitude, this.longitude, this.status, this.assignedPoliceId, this.resolvedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SosAlert.SosAlertBuilder(id=" + this.id + ", userId=" + this.userId + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", status=" + this.status + ", assignedPoliceId=" + this.assignedPoliceId + ", resolvedAt=" + this.resolvedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SosAlert.SosAlertBuilder builder() {
        return new SosAlert.SosAlertBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAssignedPoliceId() {
        return this.assignedPoliceId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setAssignedPoliceId(final Long assignedPoliceId) {
        this.assignedPoliceId = assignedPoliceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setResolvedAt(final LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    public SosAlert() {
    }

    @java.lang.SuppressWarnings("all")
    public SosAlert(final Long id, final Long userId, final Double latitude, final Double longitude, final String status, final Long assignedPoliceId, final LocalDateTime resolvedAt) {
        this.id = id;
        this.userId = userId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.status = status;
        this.assignedPoliceId = assignedPoliceId;
        this.resolvedAt = resolvedAt;
    }
}
