// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.entity;

import com.velora.user.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "emergency_contacts", indexes = {@Index(name = "idx_emergency_contacts_user_id", columnList = "user_id")})
public class EmergencyContact extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "user_id", nullable = false)
    private Long userId;
    @Column(name = "name", nullable = false, length = 100)
    private String name;
    @Column(name = "phone_number", nullable = false, length = 20)
    private String phoneNumber;
    @Column(name = "email", length = 150)
    private String email;
    @Column(name = "relationship", length = 50)
    private String relationship;
    @Column(name = "is_primary", nullable = false)
    private boolean primary;
    @Column(name = "notify_on_sos", nullable = false)
    private boolean notifyOnSos;
    @Column(name = "notify_on_route_deviation", nullable = false)
    private boolean notifyOnRouteDeviation;

    @java.lang.SuppressWarnings("all")
    private static boolean $default$primary() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$notifyOnSos() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$notifyOnRouteDeviation() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    public static class EmergencyContactBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private String email;
        @java.lang.SuppressWarnings("all")
        private String relationship;
        @java.lang.SuppressWarnings("all")
        private boolean primary$set;
        @java.lang.SuppressWarnings("all")
        private boolean primary$value;
        @java.lang.SuppressWarnings("all")
        private boolean notifyOnSos$set;
        @java.lang.SuppressWarnings("all")
        private boolean notifyOnSos$value;
        @java.lang.SuppressWarnings("all")
        private boolean notifyOnRouteDeviation$set;
        @java.lang.SuppressWarnings("all")
        private boolean notifyOnRouteDeviation$value;

        @java.lang.SuppressWarnings("all")
        EmergencyContactBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder relationship(final String relationship) {
            this.relationship = relationship;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder primary(final boolean primary) {
            this.primary$value = primary;
            primary$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder notifyOnSos(final boolean notifyOnSos) {
            this.notifyOnSos$value = notifyOnSos;
            notifyOnSos$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public EmergencyContact.EmergencyContactBuilder notifyOnRouteDeviation(final boolean notifyOnRouteDeviation) {
            this.notifyOnRouteDeviation$value = notifyOnRouteDeviation;
            notifyOnRouteDeviation$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public EmergencyContact build() {
            boolean primary$value = this.primary$value;
            if (!this.primary$set) primary$value = EmergencyContact.$default$primary();
            boolean notifyOnSos$value = this.notifyOnSos$value;
            if (!this.notifyOnSos$set) notifyOnSos$value = EmergencyContact.$default$notifyOnSos();
            boolean notifyOnRouteDeviation$value = this.notifyOnRouteDeviation$value;
            if (!this.notifyOnRouteDeviation$set) notifyOnRouteDeviation$value = EmergencyContact.$default$notifyOnRouteDeviation();
            return new EmergencyContact(this.id, this.userId, this.name, this.phoneNumber, this.email, this.relationship, primary$value, notifyOnSos$value, notifyOnRouteDeviation$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "EmergencyContact.EmergencyContactBuilder(id=" + this.id + ", userId=" + this.userId + ", name=" + this.name + ", phoneNumber=" + this.phoneNumber + ", email=" + this.email + ", relationship=" + this.relationship + ", primary$value=" + this.primary$value + ", notifyOnSos$value=" + this.notifyOnSos$value + ", notifyOnRouteDeviation$value=" + this.notifyOnRouteDeviation$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static EmergencyContact.EmergencyContactBuilder builder() {
        return new EmergencyContact.EmergencyContactBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getRelationship() {
        return this.relationship;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isPrimary() {
        return this.primary;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isNotifyOnSos() {
        return this.notifyOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isNotifyOnRouteDeviation() {
        return this.notifyOnRouteDeviation;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setRelationship(final String relationship) {
        this.relationship = relationship;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrimary(final boolean primary) {
        this.primary = primary;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotifyOnSos(final boolean notifyOnSos) {
        this.notifyOnSos = notifyOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotifyOnRouteDeviation(final boolean notifyOnRouteDeviation) {
        this.notifyOnRouteDeviation = notifyOnRouteDeviation;
    }

    @java.lang.SuppressWarnings("all")
    public EmergencyContact() {
        this.primary = EmergencyContact.$default$primary();
        this.notifyOnSos = EmergencyContact.$default$notifyOnSos();
        this.notifyOnRouteDeviation = EmergencyContact.$default$notifyOnRouteDeviation();
    }

    @java.lang.SuppressWarnings("all")
    public EmergencyContact(final Long id, final Long userId, final String name, final String phoneNumber, final String email, final String relationship, final boolean primary, final boolean notifyOnSos, final boolean notifyOnRouteDeviation) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.relationship = relationship;
        this.primary = primary;
        this.notifyOnSos = notifyOnSos;
        this.notifyOnRouteDeviation = notifyOnRouteDeviation;
    }
}
