// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "preferences")
public class UserPreference {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true)
    private Long userId;
    private boolean enableSmsAlerts = true;
    private boolean enableEmailAlerts = true;
    private boolean enablePushNotifications = true;
    private boolean shareLiveLocationWithContacts = true;
    private boolean autoTriggerPoliceCallOnSos = true;
    private String preferredMapTheme = "DARK"; // LIGHT, DARK, SATELLITE


    @java.lang.SuppressWarnings("all")
    public static class UserPreferenceBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private boolean enableSmsAlerts;
        @java.lang.SuppressWarnings("all")
        private boolean enableEmailAlerts;
        @java.lang.SuppressWarnings("all")
        private boolean enablePushNotifications;
        @java.lang.SuppressWarnings("all")
        private boolean shareLiveLocationWithContacts;
        @java.lang.SuppressWarnings("all")
        private boolean autoTriggerPoliceCallOnSos;
        @java.lang.SuppressWarnings("all")
        private String preferredMapTheme;

        @java.lang.SuppressWarnings("all")
        UserPreferenceBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder enableSmsAlerts(final boolean enableSmsAlerts) {
            this.enableSmsAlerts = enableSmsAlerts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder enableEmailAlerts(final boolean enableEmailAlerts) {
            this.enableEmailAlerts = enableEmailAlerts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder enablePushNotifications(final boolean enablePushNotifications) {
            this.enablePushNotifications = enablePushNotifications;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder shareLiveLocationWithContacts(final boolean shareLiveLocationWithContacts) {
            this.shareLiveLocationWithContacts = shareLiveLocationWithContacts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder autoTriggerPoliceCallOnSos(final boolean autoTriggerPoliceCallOnSos) {
            this.autoTriggerPoliceCallOnSos = autoTriggerPoliceCallOnSos;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserPreference.UserPreferenceBuilder preferredMapTheme(final String preferredMapTheme) {
            this.preferredMapTheme = preferredMapTheme;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public UserPreference build() {
            return new UserPreference(this.id, this.userId, this.enableSmsAlerts, this.enableEmailAlerts, this.enablePushNotifications, this.shareLiveLocationWithContacts, this.autoTriggerPoliceCallOnSos, this.preferredMapTheme);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "UserPreference.UserPreferenceBuilder(id=" + this.id + ", userId=" + this.userId + ", enableSmsAlerts=" + this.enableSmsAlerts + ", enableEmailAlerts=" + this.enableEmailAlerts + ", enablePushNotifications=" + this.enablePushNotifications + ", shareLiveLocationWithContacts=" + this.shareLiveLocationWithContacts + ", autoTriggerPoliceCallOnSos=" + this.autoTriggerPoliceCallOnSos + ", preferredMapTheme=" + this.preferredMapTheme + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static UserPreference.UserPreferenceBuilder builder() {
        return new UserPreference.UserPreferenceBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEnableSmsAlerts() {
        return this.enableSmsAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEnableEmailAlerts() {
        return this.enableEmailAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEnablePushNotifications() {
        return this.enablePushNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isShareLiveLocationWithContacts() {
        return this.shareLiveLocationWithContacts;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAutoTriggerPoliceCallOnSos() {
        return this.autoTriggerPoliceCallOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreferredMapTheme() {
        return this.preferredMapTheme;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnableSmsAlerts(final boolean enableSmsAlerts) {
        this.enableSmsAlerts = enableSmsAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnableEmailAlerts(final boolean enableEmailAlerts) {
        this.enableEmailAlerts = enableEmailAlerts;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnablePushNotifications(final boolean enablePushNotifications) {
        this.enablePushNotifications = enablePushNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setShareLiveLocationWithContacts(final boolean shareLiveLocationWithContacts) {
        this.shareLiveLocationWithContacts = shareLiveLocationWithContacts;
    }

    @java.lang.SuppressWarnings("all")
    public void setAutoTriggerPoliceCallOnSos(final boolean autoTriggerPoliceCallOnSos) {
        this.autoTriggerPoliceCallOnSos = autoTriggerPoliceCallOnSos;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreferredMapTheme(final String preferredMapTheme) {
        this.preferredMapTheme = preferredMapTheme;
    }

    @java.lang.SuppressWarnings("all")
    public UserPreference() {
    }

    @java.lang.SuppressWarnings("all")
    public UserPreference(final Long id, final Long userId, final boolean enableSmsAlerts, final boolean enableEmailAlerts, final boolean enablePushNotifications, final boolean shareLiveLocationWithContacts, final boolean autoTriggerPoliceCallOnSos, final String preferredMapTheme) {
        this.id = id;
        this.userId = userId;
        this.enableSmsAlerts = enableSmsAlerts;
        this.enableEmailAlerts = enableEmailAlerts;
        this.enablePushNotifications = enablePushNotifications;
        this.shareLiveLocationWithContacts = shareLiveLocationWithContacts;
        this.autoTriggerPoliceCallOnSos = autoTriggerPoliceCallOnSos;
        this.preferredMapTheme = preferredMapTheme;
    }
}
