// Generated by delombok at Wed Aug 05 15:39:17 IST 2026
package com.velora.user.entity;

import com.velora.user.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "user_profiles", indexes = {@Index(name = "idx_user_profiles_user_id", columnList = "user_id", unique = true)})
public class UserProfile extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "user_id", nullable = false, unique = true)
    private Long userId;
    @Column(name = "full_name", nullable = false, length = 150)
    private String fullName;
    @Column(name = "email", nullable = false, unique = true, length = 150)
    private String email;
    @Column(name = "phone_number", length = 20)
    private String phoneNumber;
    @Column(name = "profile_image_url", length = 500)
    private String profileImageUrl;
    @Column(name = "date_of_birth")
    private String dateOfBirth;
    @Column(name = "gender", length = 20)
    private String gender;
    @Column(name = "address", length = 500)
    private String address;
    @Column(name = "city", length = 100)
    private String city;
    @Column(name = "state", length = 100)
    private String state;
    @Column(name = "country", length = 100)
    private String country;
    @Column(name = "home_latitude")
    private Double homeLatitude;
    @Column(name = "home_longitude")
    private Double homeLongitude;
    @Column(name = "work_latitude")
    private Double workLatitude;
    @Column(name = "work_longitude")
    private Double workLongitude;
    @Column(name = "role", length = 50)
    private String role;
    @Column(name = "is_active", nullable = false)
    private boolean active;
    @Column(name = "notification_enabled", nullable = false)
    private boolean notificationEnabled;
    @Column(name = "location_sharing_enabled", nullable = false)
    private boolean locationSharingEnabled;
    @Column(name = "privacy_mode_enabled", nullable = false)
    private boolean privacyModeEnabled;
    @Column(name = "blood_group", length = 10)
    private String bloodGroup;
    @Column(name = "emergency_notes", length = 1000)
    private String emergencyNotes;

    @java.lang.SuppressWarnings("all")
    private static boolean $default$active() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$notificationEnabled() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$locationSharingEnabled() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$privacyModeEnabled() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    public static class UserProfileBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String fullName;
        @java.lang.SuppressWarnings("all")
        private String email;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private String profileImageUrl;
        @java.lang.SuppressWarnings("all")
        private String dateOfBirth;
        @java.lang.SuppressWarnings("all")
        private String gender;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private String city;
        @java.lang.SuppressWarnings("all")
        private String state;
        @java.lang.SuppressWarnings("all")
        private String country;
        @java.lang.SuppressWarnings("all")
        private Double homeLatitude;
        @java.lang.SuppressWarnings("all")
        private Double homeLongitude;
        @java.lang.SuppressWarnings("all")
        private Double workLatitude;
        @java.lang.SuppressWarnings("all")
        private Double workLongitude;
        @java.lang.SuppressWarnings("all")
        private String role;
        @java.lang.SuppressWarnings("all")
        private boolean active$set;
        @java.lang.SuppressWarnings("all")
        private boolean active$value;
        @java.lang.SuppressWarnings("all")
        private boolean notificationEnabled$set;
        @java.lang.SuppressWarnings("all")
        private boolean notificationEnabled$value;
        @java.lang.SuppressWarnings("all")
        private boolean locationSharingEnabled$set;
        @java.lang.SuppressWarnings("all")
        private boolean locationSharingEnabled$value;
        @java.lang.SuppressWarnings("all")
        private boolean privacyModeEnabled$set;
        @java.lang.SuppressWarnings("all")
        private boolean privacyModeEnabled$value;

        @java.lang.SuppressWarnings("all")
        UserProfileBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder fullName(final String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder profileImageUrl(final String profileImageUrl) {
            this.profileImageUrl = profileImageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder dateOfBirth(final String dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder gender(final String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder state(final String state) {
            this.state = state;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder homeLatitude(final Double homeLatitude) {
            this.homeLatitude = homeLatitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder homeLongitude(final Double homeLongitude) {
            this.homeLongitude = homeLongitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder workLatitude(final Double workLatitude) {
            this.workLatitude = workLatitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder workLongitude(final Double workLongitude) {
            this.workLongitude = workLongitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder role(final String role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder active(final boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder notificationEnabled(final boolean notificationEnabled) {
            this.notificationEnabled$value = notificationEnabled;
            notificationEnabled$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder locationSharingEnabled(final boolean locationSharingEnabled) {
            this.locationSharingEnabled$value = locationSharingEnabled;
            locationSharingEnabled$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public UserProfile.UserProfileBuilder privacyModeEnabled(final boolean privacyModeEnabled) {
            this.privacyModeEnabled$value = privacyModeEnabled;
            privacyModeEnabled$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public UserProfile build() {
            boolean active$value = this.active$value;
            if (!this.active$set) active$value = UserProfile.$default$active();
            boolean notificationEnabled$value = this.notificationEnabled$value;
            if (!this.notificationEnabled$set) notificationEnabled$value = UserProfile.$default$notificationEnabled();
            boolean locationSharingEnabled$value = this.locationSharingEnabled$value;
            if (!this.locationSharingEnabled$set) locationSharingEnabled$value = UserProfile.$default$locationSharingEnabled();
            boolean privacyModeEnabled$value = this.privacyModeEnabled$value;
            if (!this.privacyModeEnabled$set) privacyModeEnabled$value = UserProfile.$default$privacyModeEnabled();
            return new UserProfile(this.id, this.userId, this.fullName, this.email, this.phoneNumber, this.profileImageUrl, this.dateOfBirth, this.gender, this.address, this.city, this.state, this.country, this.homeLatitude, this.homeLongitude, this.workLatitude, this.workLongitude, this.role, active$value, notificationEnabled$value, locationSharingEnabled$value, privacyModeEnabled$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "UserProfile.UserProfileBuilder(id=" + this.id + ", userId=" + this.userId + ", fullName=" + this.fullName + ", email=" + this.email + ", phoneNumber=" + this.phoneNumber + ", profileImageUrl=" + this.profileImageUrl + ", dateOfBirth=" + this.dateOfBirth + ", gender=" + this.gender + ", address=" + this.address + ", city=" + this.city + ", state=" + this.state + ", country=" + this.country + ", homeLatitude=" + this.homeLatitude + ", homeLongitude=" + this.homeLongitude + ", workLatitude=" + this.workLatitude + ", workLongitude=" + this.workLongitude + ", role=" + this.role + ", active$value=" + this.active$value + ", notificationEnabled$value=" + this.notificationEnabled$value + ", locationSharingEnabled$value=" + this.locationSharingEnabled$value + ", privacyModeEnabled$value=" + this.privacyModeEnabled$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static UserProfile.UserProfileBuilder builder() {
        return new UserProfile.UserProfileBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getProfileImageUrl() {
        return this.profileImageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    public String getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public String getCountry() {
        return this.country;
    }

    @java.lang.SuppressWarnings("all")
    public Double getHomeLatitude() {
        return this.homeLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getHomeLongitude() {
        return this.homeLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getWorkLatitude() {
        return this.workLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getWorkLongitude() {
        return this.workLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isNotificationEnabled() {
        return this.notificationEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isLocationSharingEnabled() {
        return this.locationSharingEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isPrivacyModeEnabled() {
        return this.privacyModeEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setProfileImageUrl(final String profileImageUrl) {
        this.profileImageUrl = profileImageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setDateOfBirth(final String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    public void setGender(final String gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setCountry(final String country) {
        this.country = country;
    }

    @java.lang.SuppressWarnings("all")
    public void setHomeLatitude(final Double homeLatitude) {
        this.homeLatitude = homeLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setHomeLongitude(final Double homeLongitude) {
        this.homeLongitude = homeLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setWorkLatitude(final Double workLatitude) {
        this.workLatitude = workLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setWorkLongitude(final Double workLongitude) {
        this.workLongitude = workLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationEnabled(final boolean notificationEnabled) {
        this.notificationEnabled = notificationEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setLocationSharingEnabled(final boolean locationSharingEnabled) {
        this.locationSharingEnabled = locationSharingEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrivacyModeEnabled(final boolean privacyModeEnabled) {
        this.privacyModeEnabled = privacyModeEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public String getBloodGroup() {
        return this.bloodGroup;
    }

    @java.lang.SuppressWarnings("all")
    public void setBloodGroup(final String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmergencyNotes() {
        return this.emergencyNotes;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmergencyNotes(final String emergencyNotes) {
        this.emergencyNotes = emergencyNotes;
    }

    @java.lang.SuppressWarnings("all")
    public UserProfile() {
        this.active = UserProfile.$default$active();
        this.notificationEnabled = UserProfile.$default$notificationEnabled();
        this.locationSharingEnabled = UserProfile.$default$locationSharingEnabled();
        this.privacyModeEnabled = UserProfile.$default$privacyModeEnabled();
    }

    @java.lang.SuppressWarnings("all")
    public UserProfile(final Long id, final Long userId, final String fullName, final String email, final String phoneNumber, final String profileImageUrl, final String dateOfBirth, final String gender, final String address, final String city, final String state, final String country, final Double homeLatitude, final Double homeLongitude, final Double workLatitude, final Double workLongitude, final String role, final boolean active, final boolean notificationEnabled, final boolean locationSharingEnabled, final boolean privacyModeEnabled) {
        this.id = id;
        this.userId = userId;
        this.fullName = fullName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.profileImageUrl = profileImageUrl;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.address = address;
        this.city = city;
        this.state = state;
        this.country = country;
        this.homeLatitude = homeLatitude;
        this.homeLongitude = homeLongitude;
        this.workLatitude = workLatitude;
        this.workLongitude = workLongitude;
        this.role = role;
        this.active = active;
        this.notificationEnabled = notificationEnabled;
        this.locationSharingEnabled = locationSharingEnabled;
        this.privacyModeEnabled = privacyModeEnabled;
    }
}
