// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.dto;

import com.velora.safety.entity.Incident;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

public class IncidentRequest {
    @NotBlank(message = "Title is required")
    @Size(max = 200)
    private String title;
    @Size(max = 5000)
    private String description;
    @NotNull(message = "Incident type is required")
    private Incident.IncidentType incidentType;
    private Incident.IncidentSeverity severity;
    private Double latitude;
    private Double longitude;
    private String address;
    private String city;
    private String state;
    private LocalDateTime incidentDate;
    private boolean anonymous;


    @java.lang.SuppressWarnings("all")
    public static class IncidentRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String description;
        @java.lang.SuppressWarnings("all")
        private Incident.IncidentType incidentType;
        @java.lang.SuppressWarnings("all")
        private Incident.IncidentSeverity severity;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private String city;
        @java.lang.SuppressWarnings("all")
        private String state;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime incidentDate;
        @java.lang.SuppressWarnings("all")
        private boolean anonymous;

        @java.lang.SuppressWarnings("all")
        IncidentRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder incidentType(final Incident.IncidentType incidentType) {
            this.incidentType = incidentType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder severity(final Incident.IncidentSeverity severity) {
            this.severity = severity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder state(final String state) {
            this.state = state;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder incidentDate(final LocalDateTime incidentDate) {
            this.incidentDate = incidentDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentRequest.IncidentRequestBuilder anonymous(final boolean anonymous) {
            this.anonymous = anonymous;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public IncidentRequest build() {
            return new IncidentRequest(this.title, this.description, this.incidentType, this.severity, this.latitude, this.longitude, this.address, this.city, this.state, this.incidentDate, this.anonymous);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "IncidentRequest.IncidentRequestBuilder(title=" + this.title + ", description=" + this.description + ", incidentType=" + this.incidentType + ", severity=" + this.severity + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", address=" + this.address + ", city=" + this.city + ", state=" + this.state + ", incidentDate=" + this.incidentDate + ", anonymous=" + this.anonymous + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static IncidentRequest.IncidentRequestBuilder builder() {
        return new IncidentRequest.IncidentRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Incident.IncidentType getIncidentType() {
        return this.incidentType;
    }

    @java.lang.SuppressWarnings("all")
    public Incident.IncidentSeverity getSeverity() {
        return this.severity;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getIncidentDate() {
        return this.incidentDate;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAnonymous() {
        return this.anonymous;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentType(final Incident.IncidentType incidentType) {
        this.incidentType = incidentType;
    }

    @java.lang.SuppressWarnings("all")
    public void setSeverity(final Incident.IncidentSeverity severity) {
        this.severity = severity;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentDate(final LocalDateTime incidentDate) {
        this.incidentDate = incidentDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAnonymous(final boolean anonymous) {
        this.anonymous = anonymous;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IncidentRequest)) return false;
        final IncidentRequest other = (IncidentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAnonymous() != other.isAnonymous()) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$incidentType = this.getIncidentType();
        final java.lang.Object other$incidentType = other.getIncidentType();
        if (this$incidentType == null ? other$incidentType != null : !this$incidentType.equals(other$incidentType)) return false;
        final java.lang.Object this$severity = this.getSeverity();
        final java.lang.Object other$severity = other.getSeverity();
        if (this$severity == null ? other$severity != null : !this$severity.equals(other$severity)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$incidentDate = this.getIncidentDate();
        final java.lang.Object other$incidentDate = other.getIncidentDate();
        if (this$incidentDate == null ? other$incidentDate != null : !this$incidentDate.equals(other$incidentDate)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IncidentRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAnonymous() ? 79 : 97);
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $incidentType = this.getIncidentType();
        result = result * PRIME + ($incidentType == null ? 43 : $incidentType.hashCode());
        final java.lang.Object $severity = this.getSeverity();
        result = result * PRIME + ($severity == null ? 43 : $severity.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $incidentDate = this.getIncidentDate();
        result = result * PRIME + ($incidentDate == null ? 43 : $incidentDate.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "IncidentRequest(title=" + this.getTitle() + ", description=" + this.getDescription() + ", incidentType=" + this.getIncidentType() + ", severity=" + this.getSeverity() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", address=" + this.getAddress() + ", city=" + this.getCity() + ", state=" + this.getState() + ", incidentDate=" + this.getIncidentDate() + ", anonymous=" + this.isAnonymous() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public IncidentRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public IncidentRequest(final String title, final String description, final Incident.IncidentType incidentType, final Incident.IncidentSeverity severity, final Double latitude, final Double longitude, final String address, final String city, final String state, final LocalDateTime incidentDate, final boolean anonymous) {
        this.title = title;
        this.description = description;
        this.incidentType = incidentType;
        this.severity = severity;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.city = city;
        this.state = state;
        this.incidentDate = incidentDate;
        this.anonymous = anonymous;
    }
}
