// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.dto;

import com.velora.safety.entity.Incident;
import java.time.LocalDateTime;
import java.util.List;

public class IncidentResponse {
    private Long id;
    private Long reporterUserId;
    private String title;
    private String description;
    private Incident.IncidentType incidentType;
    private Incident.IncidentStatus status;
    private Incident.IncidentSeverity severity;
    private Double latitude;
    private Double longitude;
    private String address;
    private String city;
    private String state;
    private LocalDateTime incidentDate;
    private boolean anonymous;
    private Long assignedOfficerId;
    private String policeNotes;
    private LocalDateTime resolvedAt;
    private List<String> imageUrls;
    private LocalDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    public static class IncidentResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long reporterUserId;
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String description;
        @java.lang.SuppressWarnings("all")
        private Incident.IncidentType incidentType;
        @java.lang.SuppressWarnings("all")
        private Incident.IncidentStatus status;
        @java.lang.SuppressWarnings("all")
        private Incident.IncidentSeverity severity;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private String city;
        @java.lang.SuppressWarnings("all")
        private String state;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime incidentDate;
        @java.lang.SuppressWarnings("all")
        private boolean anonymous;
        @java.lang.SuppressWarnings("all")
        private Long assignedOfficerId;
        @java.lang.SuppressWarnings("all")
        private String policeNotes;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime resolvedAt;
        @java.lang.SuppressWarnings("all")
        private List<String> imageUrls;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        IncidentResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder reporterUserId(final Long reporterUserId) {
            this.reporterUserId = reporterUserId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder incidentType(final Incident.IncidentType incidentType) {
            this.incidentType = incidentType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder status(final Incident.IncidentStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder severity(final Incident.IncidentSeverity severity) {
            this.severity = severity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder state(final String state) {
            this.state = state;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder incidentDate(final LocalDateTime incidentDate) {
            this.incidentDate = incidentDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder anonymous(final boolean anonymous) {
            this.anonymous = anonymous;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder assignedOfficerId(final Long assignedOfficerId) {
            this.assignedOfficerId = assignedOfficerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder policeNotes(final String policeNotes) {
            this.policeNotes = policeNotes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder resolvedAt(final LocalDateTime resolvedAt) {
            this.resolvedAt = resolvedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder imageUrls(final List<String> imageUrls) {
            this.imageUrls = imageUrls;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IncidentResponse.IncidentResponseBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public IncidentResponse build() {
            return new IncidentResponse(this.id, this.reporterUserId, this.title, this.description, this.incidentType, this.status, this.severity, this.latitude, this.longitude, this.address, this.city, this.state, this.incidentDate, this.anonymous, this.assignedOfficerId, this.policeNotes, this.resolvedAt, this.imageUrls, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "IncidentResponse.IncidentResponseBuilder(id=" + this.id + ", reporterUserId=" + this.reporterUserId + ", title=" + this.title + ", description=" + this.description + ", incidentType=" + this.incidentType + ", status=" + this.status + ", severity=" + this.severity + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", address=" + this.address + ", city=" + this.city + ", state=" + this.state + ", incidentDate=" + this.incidentDate + ", anonymous=" + this.anonymous + ", assignedOfficerId=" + this.assignedOfficerId + ", policeNotes=" + this.policeNotes + ", resolvedAt=" + this.resolvedAt + ", imageUrls=" + this.imageUrls + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static IncidentResponse.IncidentResponseBuilder builder() {
        return new IncidentResponse.IncidentResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getReporterUserId() {
        return this.reporterUserId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Incident.IncidentType getIncidentType() {
        return this.incidentType;
    }

    @java.lang.SuppressWarnings("all")
    public Incident.IncidentStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Incident.IncidentSeverity getSeverity() {
        return this.severity;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getIncidentDate() {
        return this.incidentDate;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAnonymous() {
        return this.anonymous;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAssignedOfficerId() {
        return this.assignedOfficerId;
    }

    @java.lang.SuppressWarnings("all")
    public String getPoliceNotes() {
        return this.policeNotes;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getImageUrls() {
        return this.imageUrls;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setReporterUserId(final Long reporterUserId) {
        this.reporterUserId = reporterUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentType(final Incident.IncidentType incidentType) {
        this.incidentType = incidentType;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Incident.IncidentStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setSeverity(final Incident.IncidentSeverity severity) {
        this.severity = severity;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setIncidentDate(final LocalDateTime incidentDate) {
        this.incidentDate = incidentDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAnonymous(final boolean anonymous) {
        this.anonymous = anonymous;
    }

    @java.lang.SuppressWarnings("all")
    public void setAssignedOfficerId(final Long assignedOfficerId) {
        this.assignedOfficerId = assignedOfficerId;
    }

    @java.lang.SuppressWarnings("all")
    public void setPoliceNotes(final String policeNotes) {
        this.policeNotes = policeNotes;
    }

    @java.lang.SuppressWarnings("all")
    public void setResolvedAt(final LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setImageUrls(final List<String> imageUrls) {
        this.imageUrls = imageUrls;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IncidentResponse)) return false;
        final IncidentResponse other = (IncidentResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAnonymous() != other.isAnonymous()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$reporterUserId = this.getReporterUserId();
        final java.lang.Object other$reporterUserId = other.getReporterUserId();
        if (this$reporterUserId == null ? other$reporterUserId != null : !this$reporterUserId.equals(other$reporterUserId)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$assignedOfficerId = this.getAssignedOfficerId();
        final java.lang.Object other$assignedOfficerId = other.getAssignedOfficerId();
        if (this$assignedOfficerId == null ? other$assignedOfficerId != null : !this$assignedOfficerId.equals(other$assignedOfficerId)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$incidentType = this.getIncidentType();
        final java.lang.Object other$incidentType = other.getIncidentType();
        if (this$incidentType == null ? other$incidentType != null : !this$incidentType.equals(other$incidentType)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$severity = this.getSeverity();
        final java.lang.Object other$severity = other.getSeverity();
        if (this$severity == null ? other$severity != null : !this$severity.equals(other$severity)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$incidentDate = this.getIncidentDate();
        final java.lang.Object other$incidentDate = other.getIncidentDate();
        if (this$incidentDate == null ? other$incidentDate != null : !this$incidentDate.equals(other$incidentDate)) return false;
        final java.lang.Object this$policeNotes = this.getPoliceNotes();
        final java.lang.Object other$policeNotes = other.getPoliceNotes();
        if (this$policeNotes == null ? other$policeNotes != null : !this$policeNotes.equals(other$policeNotes)) return false;
        final java.lang.Object this$resolvedAt = this.getResolvedAt();
        final java.lang.Object other$resolvedAt = other.getResolvedAt();
        if (this$resolvedAt == null ? other$resolvedAt != null : !this$resolvedAt.equals(other$resolvedAt)) return false;
        final java.lang.Object this$imageUrls = this.getImageUrls();
        final java.lang.Object other$imageUrls = other.getImageUrls();
        if (this$imageUrls == null ? other$imageUrls != null : !this$imageUrls.equals(other$imageUrls)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IncidentResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAnonymous() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $reporterUserId = this.getReporterUserId();
        result = result * PRIME + ($reporterUserId == null ? 43 : $reporterUserId.hashCode());
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $assignedOfficerId = this.getAssignedOfficerId();
        result = result * PRIME + ($assignedOfficerId == null ? 43 : $assignedOfficerId.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $incidentType = this.getIncidentType();
        result = result * PRIME + ($incidentType == null ? 43 : $incidentType.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $severity = this.getSeverity();
        result = result * PRIME + ($severity == null ? 43 : $severity.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $incidentDate = this.getIncidentDate();
        result = result * PRIME + ($incidentDate == null ? 43 : $incidentDate.hashCode());
        final java.lang.Object $policeNotes = this.getPoliceNotes();
        result = result * PRIME + ($policeNotes == null ? 43 : $policeNotes.hashCode());
        final java.lang.Object $resolvedAt = this.getResolvedAt();
        result = result * PRIME + ($resolvedAt == null ? 43 : $resolvedAt.hashCode());
        final java.lang.Object $imageUrls = this.getImageUrls();
        result = result * PRIME + ($imageUrls == null ? 43 : $imageUrls.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "IncidentResponse(id=" + this.getId() + ", reporterUserId=" + this.getReporterUserId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", incidentType=" + this.getIncidentType() + ", status=" + this.getStatus() + ", severity=" + this.getSeverity() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", address=" + this.getAddress() + ", city=" + this.getCity() + ", state=" + this.getState() + ", incidentDate=" + this.getIncidentDate() + ", anonymous=" + this.isAnonymous() + ", assignedOfficerId=" + this.getAssignedOfficerId() + ", policeNotes=" + this.getPoliceNotes() + ", resolvedAt=" + this.getResolvedAt() + ", imageUrls=" + this.getImageUrls() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public IncidentResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public IncidentResponse(final Long id, final Long reporterUserId, final String title, final String description, final Incident.IncidentType incidentType, final Incident.IncidentStatus status, final Incident.IncidentSeverity severity, final Double latitude, final Double longitude, final String address, final String city, final String state, final LocalDateTime incidentDate, final boolean anonymous, final Long assignedOfficerId, final String policeNotes, final LocalDateTime resolvedAt, final List<String> imageUrls, final LocalDateTime createdAt) {
        this.id = id;
        this.reporterUserId = reporterUserId;
        this.title = title;
        this.description = description;
        this.incidentType = incidentType;
        this.status = status;
        this.severity = severity;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.city = city;
        this.state = state;
        this.incidentDate = incidentDate;
        this.anonymous = anonymous;
        this.assignedOfficerId = assignedOfficerId;
        this.policeNotes = policeNotes;
        this.resolvedAt = resolvedAt;
        this.imageUrls = imageUrls;
        this.createdAt = createdAt;
    }
}
