// Generated by delombok at Wed Aug 05 15:39:21 IST 2026
package com.velora.safety.dto;

public class SafeZoneDto {
    private Long id;
    private String name;
    private String category;
    private Double latitude;
    private Double longitude;
    private String address;
    private String contactNumber;
    private Double safetyRating;
    private boolean isActive;


    @java.lang.SuppressWarnings("all")
    public static class SafeZoneDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String category;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private String address;
        @java.lang.SuppressWarnings("all")
        private String contactNumber;
        @java.lang.SuppressWarnings("all")
        private Double safetyRating;
        @java.lang.SuppressWarnings("all")
        private boolean isActive;

        @java.lang.SuppressWarnings("all")
        SafeZoneDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder category(final String category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder contactNumber(final String contactNumber) {
            this.contactNumber = contactNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder safetyRating(final Double safetyRating) {
            this.safetyRating = safetyRating;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SafeZoneDto.SafeZoneDtoBuilder isActive(final boolean isActive) {
            this.isActive = isActive;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SafeZoneDto build() {
            return new SafeZoneDto(this.id, this.name, this.category, this.latitude, this.longitude, this.address, this.contactNumber, this.safetyRating, this.isActive);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SafeZoneDto.SafeZoneDtoBuilder(id=" + this.id + ", name=" + this.name + ", category=" + this.category + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", address=" + this.address + ", contactNumber=" + this.contactNumber + ", safetyRating=" + this.safetyRating + ", isActive=" + this.isActive + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SafeZoneDto.SafeZoneDtoBuilder builder() {
        return new SafeZoneDto.SafeZoneDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getContactNumber() {
        return this.contactNumber;
    }

    @java.lang.SuppressWarnings("all")
    public Double getSafetyRating() {
        return this.safetyRating;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setContactNumber(final String contactNumber) {
        this.contactNumber = contactNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyRating(final Double safetyRating) {
        this.safetyRating = safetyRating;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SafeZoneDto)) return false;
        final SafeZoneDto other = (SafeZoneDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isActive() != other.isActive()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$safetyRating = this.getSafetyRating();
        final java.lang.Object other$safetyRating = other.getSafetyRating();
        if (this$safetyRating == null ? other$safetyRating != null : !this$safetyRating.equals(other$safetyRating)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$contactNumber = this.getContactNumber();
        final java.lang.Object other$contactNumber = other.getContactNumber();
        if (this$contactNumber == null ? other$contactNumber != null : !this$contactNumber.equals(other$contactNumber)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SafeZoneDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isActive() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $safetyRating = this.getSafetyRating();
        result = result * PRIME + ($safetyRating == null ? 43 : $safetyRating.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $contactNumber = this.getContactNumber();
        result = result * PRIME + ($contactNumber == null ? 43 : $contactNumber.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SafeZoneDto(id=" + this.getId() + ", name=" + this.getName() + ", category=" + this.getCategory() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", address=" + this.getAddress() + ", contactNumber=" + this.getContactNumber() + ", safetyRating=" + this.getSafetyRating() + ", isActive=" + this.isActive() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SafeZoneDto() {
    }

    @java.lang.SuppressWarnings("all")
    public SafeZoneDto(final Long id, final String name, final String category, final Double latitude, final Double longitude, final String address, final String contactNumber, final Double safetyRating, final boolean isActive) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.contactNumber = contactNumber;
        this.safetyRating = safetyRating;
        this.isActive = isActive;
    }
}
