// Generated by delombok at Wed Aug 05 15:39:30 IST 2026
package com.velora.police.dto;

public class PoliceUnitDto {
    private Long id;
    private Long userId;
    private String stationName;
    private String badgeNumber;
    private String emergencyHotline;
    private Double currentLat;
    private Double currentLng;
    private boolean isAvailable;


    @java.lang.SuppressWarnings("all")
    public static class PoliceUnitDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String stationName;
        @java.lang.SuppressWarnings("all")
        private String badgeNumber;
        @java.lang.SuppressWarnings("all")
        private String emergencyHotline;
        @java.lang.SuppressWarnings("all")
        private Double currentLat;
        @java.lang.SuppressWarnings("all")
        private Double currentLng;
        @java.lang.SuppressWarnings("all")
        private boolean isAvailable;

        @java.lang.SuppressWarnings("all")
        PoliceUnitDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder stationName(final String stationName) {
            this.stationName = stationName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder badgeNumber(final String badgeNumber) {
            this.badgeNumber = badgeNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder emergencyHotline(final String emergencyHotline) {
            this.emergencyHotline = emergencyHotline;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder currentLat(final Double currentLat) {
            this.currentLat = currentLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder currentLng(final Double currentLng) {
            this.currentLng = currentLng;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto.PoliceUnitDtoBuilder isAvailable(final boolean isAvailable) {
            this.isAvailable = isAvailable;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PoliceUnitDto build() {
            return new PoliceUnitDto(this.id, this.userId, this.stationName, this.badgeNumber, this.emergencyHotline, this.currentLat, this.currentLng, this.isAvailable);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PoliceUnitDto.PoliceUnitDtoBuilder(id=" + this.id + ", userId=" + this.userId + ", stationName=" + this.stationName + ", badgeNumber=" + this.badgeNumber + ", emergencyHotline=" + this.emergencyHotline + ", currentLat=" + this.currentLat + ", currentLng=" + this.currentLng + ", isAvailable=" + this.isAvailable + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PoliceUnitDto.PoliceUnitDtoBuilder builder() {
        return new PoliceUnitDto.PoliceUnitDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStationName() {
        return this.stationName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBadgeNumber() {
        return this.badgeNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmergencyHotline() {
        return this.emergencyHotline;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCurrentLat() {
        return this.currentLat;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCurrentLng() {
        return this.currentLng;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAvailable() {
        return this.isAvailable;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStationName(final String stationName) {
        this.stationName = stationName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBadgeNumber(final String badgeNumber) {
        this.badgeNumber = badgeNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmergencyHotline(final String emergencyHotline) {
        this.emergencyHotline = emergencyHotline;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentLat(final Double currentLat) {
        this.currentLat = currentLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentLng(final Double currentLng) {
        this.currentLng = currentLng;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvailable(final boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PoliceUnitDto)) return false;
        final PoliceUnitDto other = (PoliceUnitDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAvailable() != other.isAvailable()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$currentLat = this.getCurrentLat();
        final java.lang.Object other$currentLat = other.getCurrentLat();
        if (this$currentLat == null ? other$currentLat != null : !this$currentLat.equals(other$currentLat)) return false;
        final java.lang.Object this$currentLng = this.getCurrentLng();
        final java.lang.Object other$currentLng = other.getCurrentLng();
        if (this$currentLng == null ? other$currentLng != null : !this$currentLng.equals(other$currentLng)) return false;
        final java.lang.Object this$stationName = this.getStationName();
        final java.lang.Object other$stationName = other.getStationName();
        if (this$stationName == null ? other$stationName != null : !this$stationName.equals(other$stationName)) return false;
        final java.lang.Object this$badgeNumber = this.getBadgeNumber();
        final java.lang.Object other$badgeNumber = other.getBadgeNumber();
        if (this$badgeNumber == null ? other$badgeNumber != null : !this$badgeNumber.equals(other$badgeNumber)) return false;
        final java.lang.Object this$emergencyHotline = this.getEmergencyHotline();
        final java.lang.Object other$emergencyHotline = other.getEmergencyHotline();
        if (this$emergencyHotline == null ? other$emergencyHotline != null : !this$emergencyHotline.equals(other$emergencyHotline)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PoliceUnitDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAvailable() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $currentLat = this.getCurrentLat();
        result = result * PRIME + ($currentLat == null ? 43 : $currentLat.hashCode());
        final java.lang.Object $currentLng = this.getCurrentLng();
        result = result * PRIME + ($currentLng == null ? 43 : $currentLng.hashCode());
        final java.lang.Object $stationName = this.getStationName();
        result = result * PRIME + ($stationName == null ? 43 : $stationName.hashCode());
        final java.lang.Object $badgeNumber = this.getBadgeNumber();
        result = result * PRIME + ($badgeNumber == null ? 43 : $badgeNumber.hashCode());
        final java.lang.Object $emergencyHotline = this.getEmergencyHotline();
        result = result * PRIME + ($emergencyHotline == null ? 43 : $emergencyHotline.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PoliceUnitDto(id=" + this.getId() + ", userId=" + this.getUserId() + ", stationName=" + this.getStationName() + ", badgeNumber=" + this.getBadgeNumber() + ", emergencyHotline=" + this.getEmergencyHotline() + ", currentLat=" + this.getCurrentLat() + ", currentLng=" + this.getCurrentLng() + ", isAvailable=" + this.isAvailable() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PoliceUnitDto() {
    }

    @java.lang.SuppressWarnings("all")
    public PoliceUnitDto(final Long id, final Long userId, final String stationName, final String badgeNumber, final String emergencyHotline, final Double currentLat, final Double currentLng, final boolean isAvailable) {
        this.id = id;
        this.userId = userId;
        this.stationName = stationName;
        this.badgeNumber = badgeNumber;
        this.emergencyHotline = emergencyHotline;
        this.currentLat = currentLat;
        this.currentLng = currentLng;
        this.isAvailable = isAvailable;
    }
}
