// Generated by delombok at Wed Aug 05 15:39:30 IST 2026
package com.velora.police.dto;

import java.time.LocalDateTime;

public class SosAlertDto {
    private Long id;
    private Long userId;
    private Double latitude;
    private Double longitude;
    private String status;
    private Long assignedPoliceId;
    private LocalDateTime createdAt;
    private LocalDateTime resolvedAt;


    @java.lang.SuppressWarnings("all")
    public static class SosAlertDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        private String status;
        @java.lang.SuppressWarnings("all")
        private Long assignedPoliceId;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime resolvedAt;

        @java.lang.SuppressWarnings("all")
        SosAlertDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder assignedPoliceId(final Long assignedPoliceId) {
            this.assignedPoliceId = assignedPoliceId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SosAlertDto.SosAlertDtoBuilder resolvedAt(final LocalDateTime resolvedAt) {
            this.resolvedAt = resolvedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SosAlertDto build() {
            return new SosAlertDto(this.id, this.userId, this.latitude, this.longitude, this.status, this.assignedPoliceId, this.createdAt, this.resolvedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SosAlertDto.SosAlertDtoBuilder(id=" + this.id + ", userId=" + this.userId + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", status=" + this.status + ", assignedPoliceId=" + this.assignedPoliceId + ", createdAt=" + this.createdAt + ", resolvedAt=" + this.resolvedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SosAlertDto.SosAlertDtoBuilder builder() {
        return new SosAlertDto.SosAlertDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAssignedPoliceId() {
        return this.assignedPoliceId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setAssignedPoliceId(final Long assignedPoliceId) {
        this.assignedPoliceId = assignedPoliceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setResolvedAt(final LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SosAlertDto)) return false;
        final SosAlertDto other = (SosAlertDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$assignedPoliceId = this.getAssignedPoliceId();
        final java.lang.Object other$assignedPoliceId = other.getAssignedPoliceId();
        if (this$assignedPoliceId == null ? other$assignedPoliceId != null : !this$assignedPoliceId.equals(other$assignedPoliceId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$resolvedAt = this.getResolvedAt();
        final java.lang.Object other$resolvedAt = other.getResolvedAt();
        if (this$resolvedAt == null ? other$resolvedAt != null : !this$resolvedAt.equals(other$resolvedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SosAlertDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $assignedPoliceId = this.getAssignedPoliceId();
        result = result * PRIME + ($assignedPoliceId == null ? 43 : $assignedPoliceId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $resolvedAt = this.getResolvedAt();
        result = result * PRIME + ($resolvedAt == null ? 43 : $resolvedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SosAlertDto(id=" + this.getId() + ", userId=" + this.getUserId() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", status=" + this.getStatus() + ", assignedPoliceId=" + this.getAssignedPoliceId() + ", createdAt=" + this.getCreatedAt() + ", resolvedAt=" + this.getResolvedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SosAlertDto() {
    }

    @java.lang.SuppressWarnings("all")
    public SosAlertDto(final Long id, final Long userId, final Double latitude, final Double longitude, final String status, final Long assignedPoliceId, final LocalDateTime createdAt, final LocalDateTime resolvedAt) {
        this.id = id;
        this.userId = userId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.status = status;
        this.assignedPoliceId = assignedPoliceId;
        this.createdAt = createdAt;
        this.resolvedAt = resolvedAt;
    }
}
