// Generated by delombok at Wed Aug 05 15:39:27 IST 2026
package com.velora.notification.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class SendNotificationRequest {
    @NotNull(message = "Recipient user ID is required")
    private Long recipientUserId;
    @NotBlank(message = "Title is required")
    private String title;
    @NotBlank(message = "Message body is required")
    private String message;
    @NotBlank(message = "Notification type is required")
    private String type;

    @java.lang.SuppressWarnings("all")
    public SendNotificationRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getRecipientUserId() {
        return this.recipientUserId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecipientUserId(final Long recipientUserId) {
        this.recipientUserId = recipientUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SendNotificationRequest)) return false;
        final SendNotificationRequest other = (SendNotificationRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$recipientUserId = this.getRecipientUserId();
        final java.lang.Object other$recipientUserId = other.getRecipientUserId();
        if (this$recipientUserId == null ? other$recipientUserId != null : !this$recipientUserId.equals(other$recipientUserId)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SendNotificationRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $recipientUserId = this.getRecipientUserId();
        result = result * PRIME + ($recipientUserId == null ? 43 : $recipientUserId.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SendNotificationRequest(recipientUserId=" + this.getRecipientUserId() + ", title=" + this.getTitle() + ", message=" + this.getMessage() + ", type=" + this.getType() + ")";
    }
}
