// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.List;

public class AiChatRequest {
    @NotBlank(message = "Message cannot be blank")
    @Size(max = 2000, message = "Message too long")
    private String message;
    private Double userLatitude;
    private Double userLongitude;
    private List<ChatMessage> history;


    public static class ChatMessage {
        private String role; // "user" or "assistant"
        private String content;

        @java.lang.SuppressWarnings("all")
        public String getRole() {
            return this.role;
        }

        @java.lang.SuppressWarnings("all")
        public String getContent() {
            return this.content;
        }

        @java.lang.SuppressWarnings("all")
        public void setRole(final String role) {
            this.role = role;
        }

        @java.lang.SuppressWarnings("all")
        public void setContent(final String content) {
            this.content = content;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AiChatRequest.ChatMessage)) return false;
            final AiChatRequest.ChatMessage other = (AiChatRequest.ChatMessage) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$role = this.getRole();
            final java.lang.Object other$role = other.getRole();
            if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
            final java.lang.Object this$content = this.getContent();
            final java.lang.Object other$content = other.getContent();
            if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AiChatRequest.ChatMessage;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $role = this.getRole();
            result = result * PRIME + ($role == null ? 43 : $role.hashCode());
            final java.lang.Object $content = this.getContent();
            result = result * PRIME + ($content == null ? 43 : $content.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AiChatRequest.ChatMessage(role=" + this.getRole() + ", content=" + this.getContent() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public ChatMessage() {
        }

        @java.lang.SuppressWarnings("all")
        public ChatMessage(final String role, final String content) {
            this.role = role;
            this.content = content;
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class AiChatRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private String message;
        @java.lang.SuppressWarnings("all")
        private Double userLatitude;
        @java.lang.SuppressWarnings("all")
        private Double userLongitude;
        @java.lang.SuppressWarnings("all")
        private List<ChatMessage> history;

        @java.lang.SuppressWarnings("all")
        AiChatRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatRequest.AiChatRequestBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatRequest.AiChatRequestBuilder userLatitude(final Double userLatitude) {
            this.userLatitude = userLatitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatRequest.AiChatRequestBuilder userLongitude(final Double userLongitude) {
            this.userLongitude = userLongitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatRequest.AiChatRequestBuilder history(final List<ChatMessage> history) {
            this.history = history;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public AiChatRequest build() {
            return new AiChatRequest(this.message, this.userLatitude, this.userLongitude, this.history);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AiChatRequest.AiChatRequestBuilder(message=" + this.message + ", userLatitude=" + this.userLatitude + ", userLongitude=" + this.userLongitude + ", history=" + this.history + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static AiChatRequest.AiChatRequestBuilder builder() {
        return new AiChatRequest.AiChatRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public Double getUserLatitude() {
        return this.userLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getUserLongitude() {
        return this.userLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public List<ChatMessage> getHistory() {
        return this.history;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserLatitude(final Double userLatitude) {
        this.userLatitude = userLatitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserLongitude(final Double userLongitude) {
        this.userLongitude = userLongitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setHistory(final List<ChatMessage> history) {
        this.history = history;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AiChatRequest)) return false;
        final AiChatRequest other = (AiChatRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userLatitude = this.getUserLatitude();
        final java.lang.Object other$userLatitude = other.getUserLatitude();
        if (this$userLatitude == null ? other$userLatitude != null : !this$userLatitude.equals(other$userLatitude)) return false;
        final java.lang.Object this$userLongitude = this.getUserLongitude();
        final java.lang.Object other$userLongitude = other.getUserLongitude();
        if (this$userLongitude == null ? other$userLongitude != null : !this$userLongitude.equals(other$userLongitude)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$history = this.getHistory();
        final java.lang.Object other$history = other.getHistory();
        if (this$history == null ? other$history != null : !this$history.equals(other$history)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AiChatRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userLatitude = this.getUserLatitude();
        result = result * PRIME + ($userLatitude == null ? 43 : $userLatitude.hashCode());
        final java.lang.Object $userLongitude = this.getUserLongitude();
        result = result * PRIME + ($userLongitude == null ? 43 : $userLongitude.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $history = this.getHistory();
        result = result * PRIME + ($history == null ? 43 : $history.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AiChatRequest(message=" + this.getMessage() + ", userLatitude=" + this.getUserLatitude() + ", userLongitude=" + this.getUserLongitude() + ", history=" + this.getHistory() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public AiChatRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public AiChatRequest(final String message, final Double userLatitude, final Double userLongitude, final List<ChatMessage> history) {
        this.message = message;
        this.userLatitude = userLatitude;
        this.userLongitude = userLongitude;
        this.history = history;
    }
}
