// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

public class AiChatResponse {
    private String message;
    private String model;
    private int tokensUsed;
    private boolean fallback;


    @java.lang.SuppressWarnings("all")
    public static class AiChatResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String message;
        @java.lang.SuppressWarnings("all")
        private String model;
        @java.lang.SuppressWarnings("all")
        private int tokensUsed;
        @java.lang.SuppressWarnings("all")
        private boolean fallback;

        @java.lang.SuppressWarnings("all")
        AiChatResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatResponse.AiChatResponseBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatResponse.AiChatResponseBuilder model(final String model) {
            this.model = model;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatResponse.AiChatResponseBuilder tokensUsed(final int tokensUsed) {
            this.tokensUsed = tokensUsed;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AiChatResponse.AiChatResponseBuilder fallback(final boolean fallback) {
            this.fallback = fallback;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public AiChatResponse build() {
            return new AiChatResponse(this.message, this.model, this.tokensUsed, this.fallback);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AiChatResponse.AiChatResponseBuilder(message=" + this.message + ", model=" + this.model + ", tokensUsed=" + this.tokensUsed + ", fallback=" + this.fallback + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static AiChatResponse.AiChatResponseBuilder builder() {
        return new AiChatResponse.AiChatResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public String getModel() {
        return this.model;
    }

    @java.lang.SuppressWarnings("all")
    public int getTokensUsed() {
        return this.tokensUsed;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isFallback() {
        return this.fallback;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setModel(final String model) {
        this.model = model;
    }

    @java.lang.SuppressWarnings("all")
    public void setTokensUsed(final int tokensUsed) {
        this.tokensUsed = tokensUsed;
    }

    @java.lang.SuppressWarnings("all")
    public void setFallback(final boolean fallback) {
        this.fallback = fallback;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AiChatResponse)) return false;
        final AiChatResponse other = (AiChatResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTokensUsed() != other.getTokensUsed()) return false;
        if (this.isFallback() != other.isFallback()) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$model = this.getModel();
        final java.lang.Object other$model = other.getModel();
        if (this$model == null ? other$model != null : !this$model.equals(other$model)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AiChatResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getTokensUsed();
        result = result * PRIME + (this.isFallback() ? 79 : 97);
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $model = this.getModel();
        result = result * PRIME + ($model == null ? 43 : $model.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AiChatResponse(message=" + this.getMessage() + ", model=" + this.getModel() + ", tokensUsed=" + this.getTokensUsed() + ", fallback=" + this.isFallback() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public AiChatResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public AiChatResponse(final String message, final String model, final int tokensUsed, final boolean fallback) {
        this.message = message;
        this.model = model;
        this.tokensUsed = tokensUsed;
        this.fallback = fallback;
    }
}
