// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

import jakarta.validation.constraints.NotNull;

public class RiskAnalysisRequest {
    @NotNull(message = "Latitude is required")
    private Double latitude;
    @NotNull(message = "Longitude is required")
    private Double longitude;
    private String timeOfDay; // DAY, NIGHT, LATE_NIGHT

    @java.lang.SuppressWarnings("all")
    public RiskAnalysisRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getTimeOfDay() {
        return this.timeOfDay;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimeOfDay(final String timeOfDay) {
        this.timeOfDay = timeOfDay;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RiskAnalysisRequest)) return false;
        final RiskAnalysisRequest other = (RiskAnalysisRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$latitude = this.getLatitude();
        final java.lang.Object other$latitude = other.getLatitude();
        if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
        final java.lang.Object this$longitude = this.getLongitude();
        final java.lang.Object other$longitude = other.getLongitude();
        if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
        final java.lang.Object this$timeOfDay = this.getTimeOfDay();
        final java.lang.Object other$timeOfDay = other.getTimeOfDay();
        if (this$timeOfDay == null ? other$timeOfDay != null : !this$timeOfDay.equals(other$timeOfDay)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RiskAnalysisRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $latitude = this.getLatitude();
        result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
        final java.lang.Object $longitude = this.getLongitude();
        result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
        final java.lang.Object $timeOfDay = this.getTimeOfDay();
        result = result * PRIME + ($timeOfDay == null ? 43 : $timeOfDay.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RiskAnalysisRequest(latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", timeOfDay=" + this.getTimeOfDay() + ")";
    }
}
