// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

public class RiskPredictionRequest {
    private double latitude;
    private double longitude;
    private String timeOfDay; // "morning", "afternoon", "evening", "night"
    private String dayOfWeek; // "Monday", etc.
    private String weatherCondition; // "clear", "rain", "fog"
    private int nearbyIncidentCount;


    @java.lang.SuppressWarnings("all")
    public static class RiskPredictionRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private double latitude;
        @java.lang.SuppressWarnings("all")
        private double longitude;
        @java.lang.SuppressWarnings("all")
        private String timeOfDay;
        @java.lang.SuppressWarnings("all")
        private String dayOfWeek;
        @java.lang.SuppressWarnings("all")
        private String weatherCondition;
        @java.lang.SuppressWarnings("all")
        private int nearbyIncidentCount;

        @java.lang.SuppressWarnings("all")
        RiskPredictionRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest.RiskPredictionRequestBuilder latitude(final double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest.RiskPredictionRequestBuilder longitude(final double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest.RiskPredictionRequestBuilder timeOfDay(final String timeOfDay) {
            this.timeOfDay = timeOfDay;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest.RiskPredictionRequestBuilder dayOfWeek(final String dayOfWeek) {
            this.dayOfWeek = dayOfWeek;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest.RiskPredictionRequestBuilder weatherCondition(final String weatherCondition) {
            this.weatherCondition = weatherCondition;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest.RiskPredictionRequestBuilder nearbyIncidentCount(final int nearbyIncidentCount) {
            this.nearbyIncidentCount = nearbyIncidentCount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RiskPredictionRequest build() {
            return new RiskPredictionRequest(this.latitude, this.longitude, this.timeOfDay, this.dayOfWeek, this.weatherCondition, this.nearbyIncidentCount);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RiskPredictionRequest.RiskPredictionRequestBuilder(latitude=" + this.latitude + ", longitude=" + this.longitude + ", timeOfDay=" + this.timeOfDay + ", dayOfWeek=" + this.dayOfWeek + ", weatherCondition=" + this.weatherCondition + ", nearbyIncidentCount=" + this.nearbyIncidentCount + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RiskPredictionRequest.RiskPredictionRequestBuilder builder() {
        return new RiskPredictionRequest.RiskPredictionRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    public double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    public String getTimeOfDay() {
        return this.timeOfDay;
    }

    @java.lang.SuppressWarnings("all")
    public String getDayOfWeek() {
        return this.dayOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    public String getWeatherCondition() {
        return this.weatherCondition;
    }

    @java.lang.SuppressWarnings("all")
    public int getNearbyIncidentCount() {
        return this.nearbyIncidentCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLatitude(final double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setLongitude(final double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimeOfDay(final String timeOfDay) {
        this.timeOfDay = timeOfDay;
    }

    @java.lang.SuppressWarnings("all")
    public void setDayOfWeek(final String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeatherCondition(final String weatherCondition) {
        this.weatherCondition = weatherCondition;
    }

    @java.lang.SuppressWarnings("all")
    public void setNearbyIncidentCount(final int nearbyIncidentCount) {
        this.nearbyIncidentCount = nearbyIncidentCount;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RiskPredictionRequest)) return false;
        final RiskPredictionRequest other = (RiskPredictionRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getLatitude(), other.getLatitude()) != 0) return false;
        if (java.lang.Double.compare(this.getLongitude(), other.getLongitude()) != 0) return false;
        if (this.getNearbyIncidentCount() != other.getNearbyIncidentCount()) return false;
        final java.lang.Object this$timeOfDay = this.getTimeOfDay();
        final java.lang.Object other$timeOfDay = other.getTimeOfDay();
        if (this$timeOfDay == null ? other$timeOfDay != null : !this$timeOfDay.equals(other$timeOfDay)) return false;
        final java.lang.Object this$dayOfWeek = this.getDayOfWeek();
        final java.lang.Object other$dayOfWeek = other.getDayOfWeek();
        if (this$dayOfWeek == null ? other$dayOfWeek != null : !this$dayOfWeek.equals(other$dayOfWeek)) return false;
        final java.lang.Object this$weatherCondition = this.getWeatherCondition();
        final java.lang.Object other$weatherCondition = other.getWeatherCondition();
        if (this$weatherCondition == null ? other$weatherCondition != null : !this$weatherCondition.equals(other$weatherCondition)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RiskPredictionRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $latitude = java.lang.Double.doubleToLongBits(this.getLatitude());
        result = result * PRIME + (int) ($latitude >>> 32 ^ $latitude);
        final long $longitude = java.lang.Double.doubleToLongBits(this.getLongitude());
        result = result * PRIME + (int) ($longitude >>> 32 ^ $longitude);
        result = result * PRIME + this.getNearbyIncidentCount();
        final java.lang.Object $timeOfDay = this.getTimeOfDay();
        result = result * PRIME + ($timeOfDay == null ? 43 : $timeOfDay.hashCode());
        final java.lang.Object $dayOfWeek = this.getDayOfWeek();
        result = result * PRIME + ($dayOfWeek == null ? 43 : $dayOfWeek.hashCode());
        final java.lang.Object $weatherCondition = this.getWeatherCondition();
        result = result * PRIME + ($weatherCondition == null ? 43 : $weatherCondition.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RiskPredictionRequest(latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", timeOfDay=" + this.getTimeOfDay() + ", dayOfWeek=" + this.getDayOfWeek() + ", weatherCondition=" + this.getWeatherCondition() + ", nearbyIncidentCount=" + this.getNearbyIncidentCount() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public RiskPredictionRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public RiskPredictionRequest(final double latitude, final double longitude, final String timeOfDay, final String dayOfWeek, final String weatherCondition, final int nearbyIncidentCount) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.timeOfDay = timeOfDay;
        this.dayOfWeek = dayOfWeek;
        this.weatherCondition = weatherCondition;
        this.nearbyIncidentCount = nearbyIncidentCount;
    }
}
