// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

import java.util.List;

public class RiskAnalysisResponse {
    private Double riskScore; // 0-100
    private String riskLevel; // LOW, MODERATE, HIGH, SEVERE
    private Double crimeDensityIndex;
    private Double lightingIndex;
    private List<String> identifiedRiskFactors;
    private List<String> safetyRecommendations;


    @java.lang.SuppressWarnings("all")
    public static class RiskAnalysisResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private Double riskScore;
        @java.lang.SuppressWarnings("all")
        private String riskLevel;
        @java.lang.SuppressWarnings("all")
        private Double crimeDensityIndex;
        @java.lang.SuppressWarnings("all")
        private Double lightingIndex;
        @java.lang.SuppressWarnings("all")
        private List<String> identifiedRiskFactors;
        @java.lang.SuppressWarnings("all")
        private List<String> safetyRecommendations;

        @java.lang.SuppressWarnings("all")
        RiskAnalysisResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse.RiskAnalysisResponseBuilder riskScore(final Double riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse.RiskAnalysisResponseBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse.RiskAnalysisResponseBuilder crimeDensityIndex(final Double crimeDensityIndex) {
            this.crimeDensityIndex = crimeDensityIndex;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse.RiskAnalysisResponseBuilder lightingIndex(final Double lightingIndex) {
            this.lightingIndex = lightingIndex;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse.RiskAnalysisResponseBuilder identifiedRiskFactors(final List<String> identifiedRiskFactors) {
            this.identifiedRiskFactors = identifiedRiskFactors;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse.RiskAnalysisResponseBuilder safetyRecommendations(final List<String> safetyRecommendations) {
            this.safetyRecommendations = safetyRecommendations;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RiskAnalysisResponse build() {
            return new RiskAnalysisResponse(this.riskScore, this.riskLevel, this.crimeDensityIndex, this.lightingIndex, this.identifiedRiskFactors, this.safetyRecommendations);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RiskAnalysisResponse.RiskAnalysisResponseBuilder(riskScore=" + this.riskScore + ", riskLevel=" + this.riskLevel + ", crimeDensityIndex=" + this.crimeDensityIndex + ", lightingIndex=" + this.lightingIndex + ", identifiedRiskFactors=" + this.identifiedRiskFactors + ", safetyRecommendations=" + this.safetyRecommendations + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RiskAnalysisResponse.RiskAnalysisResponseBuilder builder() {
        return new RiskAnalysisResponse.RiskAnalysisResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Double getRiskScore() {
        return this.riskScore;
    }

    @java.lang.SuppressWarnings("all")
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCrimeDensityIndex() {
        return this.crimeDensityIndex;
    }

    @java.lang.SuppressWarnings("all")
    public Double getLightingIndex() {
        return this.lightingIndex;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getIdentifiedRiskFactors() {
        return this.identifiedRiskFactors;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getSafetyRecommendations() {
        return this.safetyRecommendations;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskScore(final Double riskScore) {
        this.riskScore = riskScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setCrimeDensityIndex(final Double crimeDensityIndex) {
        this.crimeDensityIndex = crimeDensityIndex;
    }

    @java.lang.SuppressWarnings("all")
    public void setLightingIndex(final Double lightingIndex) {
        this.lightingIndex = lightingIndex;
    }

    @java.lang.SuppressWarnings("all")
    public void setIdentifiedRiskFactors(final List<String> identifiedRiskFactors) {
        this.identifiedRiskFactors = identifiedRiskFactors;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyRecommendations(final List<String> safetyRecommendations) {
        this.safetyRecommendations = safetyRecommendations;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RiskAnalysisResponse)) return false;
        final RiskAnalysisResponse other = (RiskAnalysisResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$riskScore = this.getRiskScore();
        final java.lang.Object other$riskScore = other.getRiskScore();
        if (this$riskScore == null ? other$riskScore != null : !this$riskScore.equals(other$riskScore)) return false;
        final java.lang.Object this$crimeDensityIndex = this.getCrimeDensityIndex();
        final java.lang.Object other$crimeDensityIndex = other.getCrimeDensityIndex();
        if (this$crimeDensityIndex == null ? other$crimeDensityIndex != null : !this$crimeDensityIndex.equals(other$crimeDensityIndex)) return false;
        final java.lang.Object this$lightingIndex = this.getLightingIndex();
        final java.lang.Object other$lightingIndex = other.getLightingIndex();
        if (this$lightingIndex == null ? other$lightingIndex != null : !this$lightingIndex.equals(other$lightingIndex)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$identifiedRiskFactors = this.getIdentifiedRiskFactors();
        final java.lang.Object other$identifiedRiskFactors = other.getIdentifiedRiskFactors();
        if (this$identifiedRiskFactors == null ? other$identifiedRiskFactors != null : !this$identifiedRiskFactors.equals(other$identifiedRiskFactors)) return false;
        final java.lang.Object this$safetyRecommendations = this.getSafetyRecommendations();
        final java.lang.Object other$safetyRecommendations = other.getSafetyRecommendations();
        if (this$safetyRecommendations == null ? other$safetyRecommendations != null : !this$safetyRecommendations.equals(other$safetyRecommendations)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RiskAnalysisResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $riskScore = this.getRiskScore();
        result = result * PRIME + ($riskScore == null ? 43 : $riskScore.hashCode());
        final java.lang.Object $crimeDensityIndex = this.getCrimeDensityIndex();
        result = result * PRIME + ($crimeDensityIndex == null ? 43 : $crimeDensityIndex.hashCode());
        final java.lang.Object $lightingIndex = this.getLightingIndex();
        result = result * PRIME + ($lightingIndex == null ? 43 : $lightingIndex.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $identifiedRiskFactors = this.getIdentifiedRiskFactors();
        result = result * PRIME + ($identifiedRiskFactors == null ? 43 : $identifiedRiskFactors.hashCode());
        final java.lang.Object $safetyRecommendations = this.getSafetyRecommendations();
        result = result * PRIME + ($safetyRecommendations == null ? 43 : $safetyRecommendations.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RiskAnalysisResponse(riskScore=" + this.getRiskScore() + ", riskLevel=" + this.getRiskLevel() + ", crimeDensityIndex=" + this.getCrimeDensityIndex() + ", lightingIndex=" + this.getLightingIndex() + ", identifiedRiskFactors=" + this.getIdentifiedRiskFactors() + ", safetyRecommendations=" + this.getSafetyRecommendations() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public RiskAnalysisResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public RiskAnalysisResponse(final Double riskScore, final String riskLevel, final Double crimeDensityIndex, final Double lightingIndex, final List<String> identifiedRiskFactors, final List<String> safetyRecommendations) {
        this.riskScore = riskScore;
        this.riskLevel = riskLevel;
        this.crimeDensityIndex = crimeDensityIndex;
        this.lightingIndex = lightingIndex;
        this.identifiedRiskFactors = identifiedRiskFactors;
        this.safetyRecommendations = safetyRecommendations;
    }
}
