// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

import java.util.List;

public class RiskPredictionResponse {
    private double riskScore; // 0.0 - 100.0
    private String riskLevel; // LOW, MEDIUM, HIGH, CRITICAL
    private String riskLabel; // Human-readable label
    private List<String> riskFactors;
    private List<String> safetyTips;
    private String recommendation;


    @java.lang.SuppressWarnings("all")
    public static class RiskPredictionResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private double riskScore;
        @java.lang.SuppressWarnings("all")
        private String riskLevel;
        @java.lang.SuppressWarnings("all")
        private String riskLabel;
        @java.lang.SuppressWarnings("all")
        private List<String> riskFactors;
        @java.lang.SuppressWarnings("all")
        private List<String> safetyTips;
        @java.lang.SuppressWarnings("all")
        private String recommendation;

        @java.lang.SuppressWarnings("all")
        RiskPredictionResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse.RiskPredictionResponseBuilder riskScore(final double riskScore) {
            this.riskScore = riskScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse.RiskPredictionResponseBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse.RiskPredictionResponseBuilder riskLabel(final String riskLabel) {
            this.riskLabel = riskLabel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse.RiskPredictionResponseBuilder riskFactors(final List<String> riskFactors) {
            this.riskFactors = riskFactors;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse.RiskPredictionResponseBuilder safetyTips(final List<String> safetyTips) {
            this.safetyTips = safetyTips;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse.RiskPredictionResponseBuilder recommendation(final String recommendation) {
            this.recommendation = recommendation;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RiskPredictionResponse build() {
            return new RiskPredictionResponse(this.riskScore, this.riskLevel, this.riskLabel, this.riskFactors, this.safetyTips, this.recommendation);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RiskPredictionResponse.RiskPredictionResponseBuilder(riskScore=" + this.riskScore + ", riskLevel=" + this.riskLevel + ", riskLabel=" + this.riskLabel + ", riskFactors=" + this.riskFactors + ", safetyTips=" + this.safetyTips + ", recommendation=" + this.recommendation + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RiskPredictionResponse.RiskPredictionResponseBuilder builder() {
        return new RiskPredictionResponse.RiskPredictionResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public double getRiskScore() {
        return this.riskScore;
    }

    @java.lang.SuppressWarnings("all")
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    public String getRiskLabel() {
        return this.riskLabel;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getRiskFactors() {
        return this.riskFactors;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getSafetyTips() {
        return this.safetyTips;
    }

    @java.lang.SuppressWarnings("all")
    public String getRecommendation() {
        return this.recommendation;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskScore(final double riskScore) {
        this.riskScore = riskScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskLabel(final String riskLabel) {
        this.riskLabel = riskLabel;
    }

    @java.lang.SuppressWarnings("all")
    public void setRiskFactors(final List<String> riskFactors) {
        this.riskFactors = riskFactors;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyTips(final List<String> safetyTips) {
        this.safetyTips = safetyTips;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecommendation(final String recommendation) {
        this.recommendation = recommendation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RiskPredictionResponse)) return false;
        final RiskPredictionResponse other = (RiskPredictionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getRiskScore(), other.getRiskScore()) != 0) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$riskLabel = this.getRiskLabel();
        final java.lang.Object other$riskLabel = other.getRiskLabel();
        if (this$riskLabel == null ? other$riskLabel != null : !this$riskLabel.equals(other$riskLabel)) return false;
        final java.lang.Object this$riskFactors = this.getRiskFactors();
        final java.lang.Object other$riskFactors = other.getRiskFactors();
        if (this$riskFactors == null ? other$riskFactors != null : !this$riskFactors.equals(other$riskFactors)) return false;
        final java.lang.Object this$safetyTips = this.getSafetyTips();
        final java.lang.Object other$safetyTips = other.getSafetyTips();
        if (this$safetyTips == null ? other$safetyTips != null : !this$safetyTips.equals(other$safetyTips)) return false;
        final java.lang.Object this$recommendation = this.getRecommendation();
        final java.lang.Object other$recommendation = other.getRecommendation();
        if (this$recommendation == null ? other$recommendation != null : !this$recommendation.equals(other$recommendation)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RiskPredictionResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $riskScore = java.lang.Double.doubleToLongBits(this.getRiskScore());
        result = result * PRIME + (int) ($riskScore >>> 32 ^ $riskScore);
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $riskLabel = this.getRiskLabel();
        result = result * PRIME + ($riskLabel == null ? 43 : $riskLabel.hashCode());
        final java.lang.Object $riskFactors = this.getRiskFactors();
        result = result * PRIME + ($riskFactors == null ? 43 : $riskFactors.hashCode());
        final java.lang.Object $safetyTips = this.getSafetyTips();
        result = result * PRIME + ($safetyTips == null ? 43 : $safetyTips.hashCode());
        final java.lang.Object $recommendation = this.getRecommendation();
        result = result * PRIME + ($recommendation == null ? 43 : $recommendation.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RiskPredictionResponse(riskScore=" + this.getRiskScore() + ", riskLevel=" + this.getRiskLevel() + ", riskLabel=" + this.getRiskLabel() + ", riskFactors=" + this.getRiskFactors() + ", safetyTips=" + this.getSafetyTips() + ", recommendation=" + this.getRecommendation() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public RiskPredictionResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public RiskPredictionResponse(final double riskScore, final String riskLevel, final String riskLabel, final List<String> riskFactors, final List<String> safetyTips, final String recommendation) {
        this.riskScore = riskScore;
        this.riskLevel = riskLevel;
        this.riskLabel = riskLabel;
        this.riskFactors = riskFactors;
        this.safetyTips = safetyTips;
        this.recommendation = recommendation;
    }
}
