// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

import java.util.List;

public class RouteRecommendationResponse {
    private String preferredRoute; // "safest" or "fastest"
    private double safetyScore;
    private String estimatedTime;
    private double estimatedDistanceKm;
    private List<String> safetyConcerns;
    private List<String> safetyTips;
    private String recommendation;
    private List<RoutePoint> waypoints;


    public static class RoutePoint {
        private double lat;
        private double lon;
        private String label;

        @java.lang.SuppressWarnings("all")
        public double getLat() {
            return this.lat;
        }

        @java.lang.SuppressWarnings("all")
        public double getLon() {
            return this.lon;
        }

        @java.lang.SuppressWarnings("all")
        public String getLabel() {
            return this.label;
        }

        @java.lang.SuppressWarnings("all")
        public void setLat(final double lat) {
            this.lat = lat;
        }

        @java.lang.SuppressWarnings("all")
        public void setLon(final double lon) {
            this.lon = lon;
        }

        @java.lang.SuppressWarnings("all")
        public void setLabel(final String label) {
            this.label = label;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof RouteRecommendationResponse.RoutePoint)) return false;
            final RouteRecommendationResponse.RoutePoint other = (RouteRecommendationResponse.RoutePoint) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (java.lang.Double.compare(this.getLat(), other.getLat()) != 0) return false;
            if (java.lang.Double.compare(this.getLon(), other.getLon()) != 0) return false;
            final java.lang.Object this$label = this.getLabel();
            final java.lang.Object other$label = other.getLabel();
            if (this$label == null ? other$label != null : !this$label.equals(other$label)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof RouteRecommendationResponse.RoutePoint;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final long $lat = java.lang.Double.doubleToLongBits(this.getLat());
            result = result * PRIME + (int) ($lat >>> 32 ^ $lat);
            final long $lon = java.lang.Double.doubleToLongBits(this.getLon());
            result = result * PRIME + (int) ($lon >>> 32 ^ $lon);
            final java.lang.Object $label = this.getLabel();
            result = result * PRIME + ($label == null ? 43 : $label.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RouteRecommendationResponse.RoutePoint(lat=" + this.getLat() + ", lon=" + this.getLon() + ", label=" + this.getLabel() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public RoutePoint(final double lat, final double lon, final String label) {
            this.lat = lat;
            this.lon = lon;
            this.label = label;
        }

        @java.lang.SuppressWarnings("all")
        public RoutePoint() {
        }
    }


    @java.lang.SuppressWarnings("all")
    public static class RouteRecommendationResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private String preferredRoute;
        @java.lang.SuppressWarnings("all")
        private double safetyScore;
        @java.lang.SuppressWarnings("all")
        private String estimatedTime;
        @java.lang.SuppressWarnings("all")
        private double estimatedDistanceKm;
        @java.lang.SuppressWarnings("all")
        private List<String> safetyConcerns;
        @java.lang.SuppressWarnings("all")
        private List<String> safetyTips;
        @java.lang.SuppressWarnings("all")
        private String recommendation;
        @java.lang.SuppressWarnings("all")
        private List<RoutePoint> waypoints;

        @java.lang.SuppressWarnings("all")
        RouteRecommendationResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder preferredRoute(final String preferredRoute) {
            this.preferredRoute = preferredRoute;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder safetyScore(final double safetyScore) {
            this.safetyScore = safetyScore;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder estimatedTime(final String estimatedTime) {
            this.estimatedTime = estimatedTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder estimatedDistanceKm(final double estimatedDistanceKm) {
            this.estimatedDistanceKm = estimatedDistanceKm;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder safetyConcerns(final List<String> safetyConcerns) {
            this.safetyConcerns = safetyConcerns;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder safetyTips(final List<String> safetyTips) {
            this.safetyTips = safetyTips;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder recommendation(final String recommendation) {
            this.recommendation = recommendation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse.RouteRecommendationResponseBuilder waypoints(final List<RoutePoint> waypoints) {
            this.waypoints = waypoints;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RouteRecommendationResponse build() {
            return new RouteRecommendationResponse(this.preferredRoute, this.safetyScore, this.estimatedTime, this.estimatedDistanceKm, this.safetyConcerns, this.safetyTips, this.recommendation, this.waypoints);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RouteRecommendationResponse.RouteRecommendationResponseBuilder(preferredRoute=" + this.preferredRoute + ", safetyScore=" + this.safetyScore + ", estimatedTime=" + this.estimatedTime + ", estimatedDistanceKm=" + this.estimatedDistanceKm + ", safetyConcerns=" + this.safetyConcerns + ", safetyTips=" + this.safetyTips + ", recommendation=" + this.recommendation + ", waypoints=" + this.waypoints + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RouteRecommendationResponse.RouteRecommendationResponseBuilder builder() {
        return new RouteRecommendationResponse.RouteRecommendationResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getPreferredRoute() {
        return this.preferredRoute;
    }

    @java.lang.SuppressWarnings("all")
    public double getSafetyScore() {
        return this.safetyScore;
    }

    @java.lang.SuppressWarnings("all")
    public String getEstimatedTime() {
        return this.estimatedTime;
    }

    @java.lang.SuppressWarnings("all")
    public double getEstimatedDistanceKm() {
        return this.estimatedDistanceKm;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getSafetyConcerns() {
        return this.safetyConcerns;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getSafetyTips() {
        return this.safetyTips;
    }

    @java.lang.SuppressWarnings("all")
    public String getRecommendation() {
        return this.recommendation;
    }

    @java.lang.SuppressWarnings("all")
    public List<RoutePoint> getWaypoints() {
        return this.waypoints;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreferredRoute(final String preferredRoute) {
        this.preferredRoute = preferredRoute;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyScore(final double safetyScore) {
        this.safetyScore = safetyScore;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstimatedTime(final String estimatedTime) {
        this.estimatedTime = estimatedTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstimatedDistanceKm(final double estimatedDistanceKm) {
        this.estimatedDistanceKm = estimatedDistanceKm;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyConcerns(final List<String> safetyConcerns) {
        this.safetyConcerns = safetyConcerns;
    }

    @java.lang.SuppressWarnings("all")
    public void setSafetyTips(final List<String> safetyTips) {
        this.safetyTips = safetyTips;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecommendation(final String recommendation) {
        this.recommendation = recommendation;
    }

    @java.lang.SuppressWarnings("all")
    public void setWaypoints(final List<RoutePoint> waypoints) {
        this.waypoints = waypoints;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RouteRecommendationResponse)) return false;
        final RouteRecommendationResponse other = (RouteRecommendationResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getSafetyScore(), other.getSafetyScore()) != 0) return false;
        if (java.lang.Double.compare(this.getEstimatedDistanceKm(), other.getEstimatedDistanceKm()) != 0) return false;
        final java.lang.Object this$preferredRoute = this.getPreferredRoute();
        final java.lang.Object other$preferredRoute = other.getPreferredRoute();
        if (this$preferredRoute == null ? other$preferredRoute != null : !this$preferredRoute.equals(other$preferredRoute)) return false;
        final java.lang.Object this$estimatedTime = this.getEstimatedTime();
        final java.lang.Object other$estimatedTime = other.getEstimatedTime();
        if (this$estimatedTime == null ? other$estimatedTime != null : !this$estimatedTime.equals(other$estimatedTime)) return false;
        final java.lang.Object this$safetyConcerns = this.getSafetyConcerns();
        final java.lang.Object other$safetyConcerns = other.getSafetyConcerns();
        if (this$safetyConcerns == null ? other$safetyConcerns != null : !this$safetyConcerns.equals(other$safetyConcerns)) return false;
        final java.lang.Object this$safetyTips = this.getSafetyTips();
        final java.lang.Object other$safetyTips = other.getSafetyTips();
        if (this$safetyTips == null ? other$safetyTips != null : !this$safetyTips.equals(other$safetyTips)) return false;
        final java.lang.Object this$recommendation = this.getRecommendation();
        final java.lang.Object other$recommendation = other.getRecommendation();
        if (this$recommendation == null ? other$recommendation != null : !this$recommendation.equals(other$recommendation)) return false;
        final java.lang.Object this$waypoints = this.getWaypoints();
        final java.lang.Object other$waypoints = other.getWaypoints();
        if (this$waypoints == null ? other$waypoints != null : !this$waypoints.equals(other$waypoints)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RouteRecommendationResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $safetyScore = java.lang.Double.doubleToLongBits(this.getSafetyScore());
        result = result * PRIME + (int) ($safetyScore >>> 32 ^ $safetyScore);
        final long $estimatedDistanceKm = java.lang.Double.doubleToLongBits(this.getEstimatedDistanceKm());
        result = result * PRIME + (int) ($estimatedDistanceKm >>> 32 ^ $estimatedDistanceKm);
        final java.lang.Object $preferredRoute = this.getPreferredRoute();
        result = result * PRIME + ($preferredRoute == null ? 43 : $preferredRoute.hashCode());
        final java.lang.Object $estimatedTime = this.getEstimatedTime();
        result = result * PRIME + ($estimatedTime == null ? 43 : $estimatedTime.hashCode());
        final java.lang.Object $safetyConcerns = this.getSafetyConcerns();
        result = result * PRIME + ($safetyConcerns == null ? 43 : $safetyConcerns.hashCode());
        final java.lang.Object $safetyTips = this.getSafetyTips();
        result = result * PRIME + ($safetyTips == null ? 43 : $safetyTips.hashCode());
        final java.lang.Object $recommendation = this.getRecommendation();
        result = result * PRIME + ($recommendation == null ? 43 : $recommendation.hashCode());
        final java.lang.Object $waypoints = this.getWaypoints();
        result = result * PRIME + ($waypoints == null ? 43 : $waypoints.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RouteRecommendationResponse(preferredRoute=" + this.getPreferredRoute() + ", safetyScore=" + this.getSafetyScore() + ", estimatedTime=" + this.getEstimatedTime() + ", estimatedDistanceKm=" + this.getEstimatedDistanceKm() + ", safetyConcerns=" + this.getSafetyConcerns() + ", safetyTips=" + this.getSafetyTips() + ", recommendation=" + this.getRecommendation() + ", waypoints=" + this.getWaypoints() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public RouteRecommendationResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public RouteRecommendationResponse(final String preferredRoute, final double safetyScore, final String estimatedTime, final double estimatedDistanceKm, final List<String> safetyConcerns, final List<String> safetyTips, final String recommendation, final List<RoutePoint> waypoints) {
        this.preferredRoute = preferredRoute;
        this.safetyScore = safetyScore;
        this.estimatedTime = estimatedTime;
        this.estimatedDistanceKm = estimatedDistanceKm;
        this.safetyConcerns = safetyConcerns;
        this.safetyTips = safetyTips;
        this.recommendation = recommendation;
        this.waypoints = waypoints;
    }
}
