// Generated by delombok at Wed Aug 05 15:39:24 IST 2026
package com.velora.ai.dto;

import java.util.List;

public class RouteRecommendationRequest {
    private double originLat;
    private double originLon;
    private double destinationLat;
    private double destinationLon;
    private String preference; // "safest", "fastest", "balanced"


    @java.lang.SuppressWarnings("all")
    public static class RouteRecommendationRequestBuilder {
        @java.lang.SuppressWarnings("all")
        private double originLat;
        @java.lang.SuppressWarnings("all")
        private double originLon;
        @java.lang.SuppressWarnings("all")
        private double destinationLat;
        @java.lang.SuppressWarnings("all")
        private double destinationLon;
        @java.lang.SuppressWarnings("all")
        private String preference;

        @java.lang.SuppressWarnings("all")
        RouteRecommendationRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationRequest.RouteRecommendationRequestBuilder originLat(final double originLat) {
            this.originLat = originLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationRequest.RouteRecommendationRequestBuilder originLon(final double originLon) {
            this.originLon = originLon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationRequest.RouteRecommendationRequestBuilder destinationLat(final double destinationLat) {
            this.destinationLat = destinationLat;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationRequest.RouteRecommendationRequestBuilder destinationLon(final double destinationLon) {
            this.destinationLon = destinationLon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public RouteRecommendationRequest.RouteRecommendationRequestBuilder preference(final String preference) {
            this.preference = preference;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RouteRecommendationRequest build() {
            return new RouteRecommendationRequest(this.originLat, this.originLon, this.destinationLat, this.destinationLon, this.preference);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "RouteRecommendationRequest.RouteRecommendationRequestBuilder(originLat=" + this.originLat + ", originLon=" + this.originLon + ", destinationLat=" + this.destinationLat + ", destinationLon=" + this.destinationLon + ", preference=" + this.preference + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RouteRecommendationRequest.RouteRecommendationRequestBuilder builder() {
        return new RouteRecommendationRequest.RouteRecommendationRequestBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public double getOriginLat() {
        return this.originLat;
    }

    @java.lang.SuppressWarnings("all")
    public double getOriginLon() {
        return this.originLon;
    }

    @java.lang.SuppressWarnings("all")
    public double getDestinationLat() {
        return this.destinationLat;
    }

    @java.lang.SuppressWarnings("all")
    public double getDestinationLon() {
        return this.destinationLon;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreference() {
        return this.preference;
    }

    @java.lang.SuppressWarnings("all")
    public void setOriginLat(final double originLat) {
        this.originLat = originLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setOriginLon(final double originLon) {
        this.originLon = originLon;
    }

    @java.lang.SuppressWarnings("all")
    public void setDestinationLat(final double destinationLat) {
        this.destinationLat = destinationLat;
    }

    @java.lang.SuppressWarnings("all")
    public void setDestinationLon(final double destinationLon) {
        this.destinationLon = destinationLon;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreference(final String preference) {
        this.preference = preference;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RouteRecommendationRequest)) return false;
        final RouteRecommendationRequest other = (RouteRecommendationRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (java.lang.Double.compare(this.getOriginLat(), other.getOriginLat()) != 0) return false;
        if (java.lang.Double.compare(this.getOriginLon(), other.getOriginLon()) != 0) return false;
        if (java.lang.Double.compare(this.getDestinationLat(), other.getDestinationLat()) != 0) return false;
        if (java.lang.Double.compare(this.getDestinationLon(), other.getDestinationLon()) != 0) return false;
        final java.lang.Object this$preference = this.getPreference();
        final java.lang.Object other$preference = other.getPreference();
        if (this$preference == null ? other$preference != null : !this$preference.equals(other$preference)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RouteRecommendationRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $originLat = java.lang.Double.doubleToLongBits(this.getOriginLat());
        result = result * PRIME + (int) ($originLat >>> 32 ^ $originLat);
        final long $originLon = java.lang.Double.doubleToLongBits(this.getOriginLon());
        result = result * PRIME + (int) ($originLon >>> 32 ^ $originLon);
        final long $destinationLat = java.lang.Double.doubleToLongBits(this.getDestinationLat());
        result = result * PRIME + (int) ($destinationLat >>> 32 ^ $destinationLat);
        final long $destinationLon = java.lang.Double.doubleToLongBits(this.getDestinationLon());
        result = result * PRIME + (int) ($destinationLon >>> 32 ^ $destinationLon);
        final java.lang.Object $preference = this.getPreference();
        result = result * PRIME + ($preference == null ? 43 : $preference.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RouteRecommendationRequest(originLat=" + this.getOriginLat() + ", originLon=" + this.getOriginLon() + ", destinationLat=" + this.getDestinationLat() + ", destinationLon=" + this.getDestinationLon() + ", preference=" + this.getPreference() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public RouteRecommendationRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public RouteRecommendationRequest(final double originLat, final double originLon, final double destinationLat, final double destinationLon, final String preference) {
        this.originLat = originLat;
        this.originLon = originLon;
        this.destinationLat = destinationLat;
        this.destinationLon = destinationLon;
        this.preference = preference;
    }
}
