// Generated by delombok at Wed Aug 05 15:39:33 IST 2026
package com.velora.admin.entity;

import com.velora.admin.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "admin_logs")
public class AdminLog extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Long adminUserId;
    @Column(nullable = false, length = 100)
    private String action;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String details;
    @Column(length = 45)
    private String ipAddress;


    @java.lang.SuppressWarnings("all")
    public static class AdminLogBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long adminUserId;
        @java.lang.SuppressWarnings("all")
        private String action;
        @java.lang.SuppressWarnings("all")
        private String details;
        @java.lang.SuppressWarnings("all")
        private String ipAddress;

        @java.lang.SuppressWarnings("all")
        AdminLogBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AdminLog.AdminLogBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AdminLog.AdminLogBuilder adminUserId(final Long adminUserId) {
            this.adminUserId = adminUserId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AdminLog.AdminLogBuilder action(final String action) {
            this.action = action;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AdminLog.AdminLogBuilder details(final String details) {
            this.details = details;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AdminLog.AdminLogBuilder ipAddress(final String ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public AdminLog build() {
            return new AdminLog(this.id, this.adminUserId, this.action, this.details, this.ipAddress);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AdminLog.AdminLogBuilder(id=" + this.id + ", adminUserId=" + this.adminUserId + ", action=" + this.action + ", details=" + this.details + ", ipAddress=" + this.ipAddress + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static AdminLog.AdminLogBuilder builder() {
        return new AdminLog.AdminLogBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAdminUserId() {
        return this.adminUserId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAction() {
        return this.action;
    }

    @java.lang.SuppressWarnings("all")
    public String getDetails() {
        return this.details;
    }

    @java.lang.SuppressWarnings("all")
    public String getIpAddress() {
        return this.ipAddress;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setAdminUserId(final Long adminUserId) {
        this.adminUserId = adminUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAction(final String action) {
        this.action = action;
    }

    @java.lang.SuppressWarnings("all")
    public void setDetails(final String details) {
        this.details = details;
    }

    @java.lang.SuppressWarnings("all")
    public void setIpAddress(final String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @java.lang.SuppressWarnings("all")
    public AdminLog() {
    }

    @java.lang.SuppressWarnings("all")
    public AdminLog(final Long id, final Long adminUserId, final String action, final String details, final String ipAddress) {
        this.id = id;
        this.adminUserId = adminUserId;
        this.action = action;
        this.details = details;
        this.ipAddress = ipAddress;
    }
}
