// Generated by delombok at Wed Aug 05 15:39:33 IST 2026
package com.velora.admin.entity;

import com.velora.admin.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "system_settings")
public class SystemSetting extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, unique = true, length = 100)
    private String settingKey;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String settingValue;
    @Column(length = 255)
    private String description;


    @java.lang.SuppressWarnings("all")
    public static class SystemSettingBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String settingKey;
        @java.lang.SuppressWarnings("all")
        private String settingValue;
        @java.lang.SuppressWarnings("all")
        private String description;

        @java.lang.SuppressWarnings("all")
        SystemSettingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSetting.SystemSettingBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSetting.SystemSettingBuilder settingKey(final String settingKey) {
            this.settingKey = settingKey;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSetting.SystemSettingBuilder settingValue(final String settingValue) {
            this.settingValue = settingValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SystemSetting.SystemSettingBuilder description(final String description) {
            this.description = description;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SystemSetting build() {
            return new SystemSetting(this.id, this.settingKey, this.settingValue, this.description);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SystemSetting.SystemSettingBuilder(id=" + this.id + ", settingKey=" + this.settingKey + ", settingValue=" + this.settingValue + ", description=" + this.description + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SystemSetting.SystemSettingBuilder builder() {
        return new SystemSetting.SystemSettingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getSettingKey() {
        return this.settingKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getSettingValue() {
        return this.settingValue;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSettingKey(final String settingKey) {
        this.settingKey = settingKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setSettingValue(final String settingValue) {
        this.settingValue = settingValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public SystemSetting() {
    }

    @java.lang.SuppressWarnings("all")
    public SystemSetting(final Long id, final String settingKey, final String settingValue, final String description) {
        this.id = id;
        this.settingKey = settingKey;
        this.settingValue = settingValue;
        this.description = description;
    }
}
