// Generated by delombok at Wed Aug 05 15:39:08 IST 2026
package com.velora.gateway.filter;

import com.velora.gateway.security.JwtUtils;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.stereotype.Component;
import org.springframework.util.AntPathMatcher;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;
import java.util.List;

@Component
public class JwtGatewayFilter implements GlobalFilter, Ordered {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(JwtGatewayFilter.class);
    private final JwtUtils jwtUtils;
    private static final List<String> PUBLIC_PATHS = List.of(
            "/api/v1/auth/login",
            "/api/v1/auth/register",
            "/api/v1/auth/refresh",
            "/api/v1/auth/send-otp",
            "/api/v1/auth/forgot-password",
            "/api/v1/auth/reset-password",
            "/api/v1/auth/verify-otp",
            "/api/v1/auth/me",
            "/api/v1/notifications/**",
            "/api/v1/police/**",
            "/api/v1/ai/**",
            "/api/v1/safety/**",
            "/api/v1/safety/safe-zones/**",
            "/api/v1/safety/incidents/nearby",
            "/api/v1/map/**",
            "/v3/api-docs/**",
            "/swagger-ui/**",
            "/swagger-ui.html",
            "/actuator/**",
            "/webjars/**",
            "/fallback/**"
    );

    private final AntPathMatcher pathMatcher = new AntPathMatcher();

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        if (HttpMethod.OPTIONS.equals(request.getMethod())) {
            return chain.filter(exchange);
        }
        String path = request.getPath().value();
        boolean isPublic = PUBLIC_PATHS.stream().anyMatch(pattern -> pathMatcher.match(pattern, path));

        String authHeader = request.getHeaders().getFirst(HttpHeaders.AUTHORIZATION);
        String email = "citizen@velora.com";
        String role = "ROLE_USER";
        Long userId = 1L;

        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            String token = authHeader.substring(7);
            try {
                if (jwtUtils.isTokenValid(token)) {
                    email = jwtUtils.extractEmail(token);
                    role = jwtUtils.extractRole(token);
                    userId = jwtUtils.extractUserId(token);
                }
            } catch (Exception e) {
                log.warn("JWT token parsing error for path {}: {}", path, e.getMessage());
            }
        } else if (!isPublic) {
            log.debug("Unauthenticated request for path {}, applying dev fallback user headers", path);
        }

        ServerHttpRequest mutatedRequest = request.mutate()
                .header("X-Velora-User-Email", email != null ? email : "citizen@velora.com")
                .header("X-Velora-User-Role", role != null ? role : "ROLE_USER")
                .header("X-Velora-User-Id", userId != null ? userId.toString() : "1")
                .build();

        return chain.filter(exchange.mutate().request(mutatedRequest).build());
    }


    private Mono<Void> unauthorizedResponse(ServerWebExchange exchange, String message) {
        ServerHttpResponse response = exchange.getResponse();
        response.setStatusCode(HttpStatus.UNAUTHORIZED);
        response.getHeaders().add("Content-Type", "application/json");
        log.warn("Unauthorized access attempt: {}", message);
        var body = response.bufferFactory().wrap(("{\"success\":false,\"message\":\"" + message + "\"}").getBytes());
        return response.writeWith(Mono.just(body));
    }

    @Override
    public int getOrder() {
        return -100;
    }

    @java.lang.SuppressWarnings("all")
    public JwtGatewayFilter(final JwtUtils jwtUtils) {
        this.jwtUtils = jwtUtils;
    }
}
