// Generated by delombok at Wed Aug 05 15:39:08 IST 2026
package com.velora.gateway.filter;

import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;
import java.time.Instant;

@Component
public class RequestLoggingFilter implements GlobalFilter, Ordered {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(RequestLoggingFilter.class);

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        long startTime = System.currentTimeMillis();
        String requestId = request.getId();
        log.info("[{}] --> {} {}", requestId, request.getMethod(), request.getPath());
        return chain.filter(exchange).then(Mono.fromRunnable(() -> {
            ServerHttpResponse response = exchange.getResponse();
            long duration = System.currentTimeMillis() - startTime;
            log.info("[{}] <-- {} {} | Status: {} | {}ms", requestId, request.getMethod(), request.getPath(), response.getStatusCode(), duration);
        }));
    }

    @Override
    public int getOrder() {
        return -200;
    }
}
