// Generated by delombok at Wed Aug 05 15:39:27 IST 2026
package com.velora.notification.entity;

import com.velora.notification.common.BaseAuditableEntity;
import jakarta.persistence.*;

@Entity
@Table(name = "notifications", indexes = {@Index(name = "idx_notifications_user", columnList = "user_id"), @Index(name = "idx_notifications_read", columnList = "is_read")})
public class Notification extends BaseAuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "user_id", nullable = false)
    private Long userId;
    @Column(name = "title", nullable = false, length = 200)
    private String title;
    @Column(name = "message", columnDefinition = "TEXT", nullable = false)
    private String message;
    @Column(name = "type", columnDefinition = "VARCHAR(50)")
    @Enumerated(EnumType.STRING)
    private NotificationType type;
    @Column(name = "is_read", nullable = false)
    private boolean read;
    @Column(name = "action_url", length = 500)
    private String actionUrl;
    @Column(name = "reference_id")
    private Long referenceId;
    @Column(name = "reference_type", length = 50)
    private String referenceType;


    public enum NotificationType {
        INFO, WARNING, ALERT, SOS, INCIDENT_UPDATE, SYSTEM;
    }

    @java.lang.SuppressWarnings("all")
    private static NotificationType $default$type() {
        return NotificationType.INFO;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$read() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    public static class NotificationBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String message;
        @java.lang.SuppressWarnings("all")
        private boolean type$set;
        @java.lang.SuppressWarnings("all")
        private NotificationType type$value;
        @java.lang.SuppressWarnings("all")
        private boolean read$set;
        @java.lang.SuppressWarnings("all")
        private boolean read$value;
        @java.lang.SuppressWarnings("all")
        private String actionUrl;
        @java.lang.SuppressWarnings("all")
        private Long referenceId;
        @java.lang.SuppressWarnings("all")
        private String referenceType;

        @java.lang.SuppressWarnings("all")
        NotificationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder type(final NotificationType type) {
            this.type$value = type;
            type$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder read(final boolean read) {
            this.read$value = read;
            read$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder actionUrl(final String actionUrl) {
            this.actionUrl = actionUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder referenceId(final Long referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder referenceType(final String referenceType) {
            this.referenceType = referenceType;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Notification build() {
            NotificationType type$value = this.type$value;
            if (!this.type$set) type$value = Notification.$default$type();
            boolean read$value = this.read$value;
            if (!this.read$set) read$value = Notification.$default$read();
            return new Notification(this.id, this.userId, this.title, this.message, type$value, read$value, this.actionUrl, this.referenceId, this.referenceType);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Notification.NotificationBuilder(id=" + this.id + ", userId=" + this.userId + ", title=" + this.title + ", message=" + this.message + ", type$value=" + this.type$value + ", read$value=" + this.read$value + ", actionUrl=" + this.actionUrl + ", referenceId=" + this.referenceId + ", referenceType=" + this.referenceType + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Notification.NotificationBuilder builder() {
        return new Notification.NotificationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public NotificationType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isRead() {
        return this.read;
    }

    @java.lang.SuppressWarnings("all")
    public String getActionUrl() {
        return this.actionUrl;
    }

    @java.lang.SuppressWarnings("all")
    public Long getReferenceId() {
        return this.referenceId;
    }

    @java.lang.SuppressWarnings("all")
    public String getReferenceType() {
        return this.referenceType;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final NotificationType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setRead(final boolean read) {
        this.read = read;
    }

    @java.lang.SuppressWarnings("all")
    public void setActionUrl(final String actionUrl) {
        this.actionUrl = actionUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setReferenceId(final Long referenceId) {
        this.referenceId = referenceId;
    }

    @java.lang.SuppressWarnings("all")
    public void setReferenceType(final String referenceType) {
        this.referenceType = referenceType;
    }

    @java.lang.SuppressWarnings("all")
    public Notification() {
        this.type = Notification.$default$type();
        this.read = Notification.$default$read();
    }

    @java.lang.SuppressWarnings("all")
    public Notification(final Long id, final Long userId, final String title, final String message, final NotificationType type, final boolean read, final String actionUrl, final Long referenceId, final String referenceType) {
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.message = message;
        this.type = type;
        this.read = read;
        this.actionUrl = actionUrl;
        this.referenceId = referenceId;
        this.referenceType = referenceType;
    }
}
